### ISSUE TITLE
default path to auth.json

### ISSUE THREAD

**Issue by vrothberg** [containers/image#1125]
Unless specified by the user, the `auth.json` defaults to `$XDG_RUNTIME_DIR/...` when set or `/run/containers/%UID/auth.json`.

There are a couple of things to unpack:

1. The config won't persist over a reboot.  Note that this is Linux-only, Mac and Windows store it under `$HOME/...`
2. It's causing odd behaviours when running as root where `$XDG_RUNTIME_DIR` is not set in systemd services. That's unfortunate when running podman in systemd services (e.g., to serve API requests).

@giuseppe mentioned that root should ignore XDG_RUNTIME_DIR as done in other places.  However that may impact backwards compat.

I want to prevent Podman from hard-coding another default so that all consumers of c/image can continue working together.

@mtrmac @giuseppe @rhatdan PTAL

@baude @mheon @jwhonce FYI

**Comment by psgreco** [comment]
Backwards compat is relative, right? because with current settings, under linux users should expect auth.js to be removed on reboot, so everything should be prepared to login on reboot

**Comment by vrothberg** [comment]
I am mostly concerned about changing defaults.  Some users may expect the current behaviour.

**Comment by giuseppe** [comment]
I wasn't aware of `/run/containers/%UID/auth.json`.  How is it supposed to work for UIDs != 0?  Unprivileged users have no write access to `/run/containers`.

**Comment by TomSweeneyRedHat** [comment]
ping @QiWang19 in case she hasn't seen this and wants to chime in.

**Comment by TomSweeneyRedHat** [comment]
FWIW, the placement under the `/run` directory was intentional so that the file would be removed after reboot, helping things be a bit more secure.  at least that was the thinking.  The systemd issue that @psgreco ran into was not anticipated.  I'm not sure the /run/containers location will work as @giuseppe pointed out for rootless users as a default.  That might be another thing to tinker with if that's indeed the default if XDG_RUNTIME_DIR is unset.

**Comment by QiWang19** [comment]
From the code looks like other tools should check and set the  `/run/user/$UID` to avoid the /run/containers/%UID/auth.json for UIDs != 0.

**Comment by cevich** [comment]
> /run/containers/%UID/auth.json

I can definitively attest to this being horribly broken default for rootless.  It seems that `podman` accidentally gets around this by ([reportedly](https://github.com/containers/skopeo/issues/823#issuecomment-878576580)) forcing XDG_RUNTIME_DIR to `/tmp/podman-run-$uid`.  Otherwise, the actual default is broken for all rootless users of this library.  I propose that we [change the fall-back default](https://github.com/containers/image/blob/5a7aad2b495a6aa4b16ab07819a25524a73e838d/pkg/docker/config/config.go#L41) to formally specify `/tmp/$cmd-run-$uid/containers` (along with downstream plumbing to fill in $cmd).  Since there are so many corner-cases involved, keeping a per-command directory as a fall-back seems to be the least-worst option.  I would also suggest that along with the downstream changes to support this, tools should also throw a warning when the fallback default is in effect:  

    Warning: Storing runtime details under /tmp is slightly unsafe,
    consider overriding XDG_RUNTIME_DIR to a private temporary
    location

**Comment by rhatdan** [comment]
Well if you add this warning, make sure /tmp is not on a tmpfs as it is on all RHEL/Fedora/Centos platforms by default.

$ grep /tmp /proc/self/mountinfo 
94 89 0:38 / /tmp rw,nosuid,nodev shared:46 - tmpfs tmpfs rw,seclabel,size=8008736k,nr_inodes=409600,inode64

**Comment by cevich** [comment]
Hmmm.  Maybe `/var/tmp` then?  Or would somewhere under `$HOME` be a better default fallback choice?  Though there are cases where it's unset as well, having it as a requirement normally doesn't cause much friction.  I would think `$HOME` would be slightly safer than `/tmp/...` as well.

**Comment by rhatdan** [comment]
Sure.

**Comment by mtrmac** [comment]
Let’s continue in #1097, please, so that we don’t have separate conversations; and that one already has more detailed links to the historical rationale.

I’ll also try to summarize everything in there, including the conversations from this issue, but don’t hesitate to speak up if that summary missed something.
