### ISSUE TITLE
Default unqualified images to docker.io

### ISSUE THREAD

**Issue by AstraLuma** [containers/image#1149]
This feels like it's going to be an uphill battle, so I'm going to lay this out.

Yes, Docker Hub as the default ultimately does harm to the container ecosystem.

But interoperability is very important.

This decision causes ripple effects, like "podman is a drop-in replacement for docker, except for image names" or larger things like "cirrus cli (which depends on podman/docker) can't run pipelines locally".

Of course, "just edit your call" or "adjust your config" will do this, but 1. enterprise environments can make this hard, 2. why is the default incompatible?

**Comment by rhatdan** [comment]
How exactly are we not compatible? Docker.io is in the list of registries, so it should just work.

**Comment by AstraLuma** [comment]
The default `registries.conf` does not list docker.io in `unqualified-search-registries`.

So if the user is expected to be able to run `podman run postgres` (picked something not on the alias list) or `podman run xonsh/xonsh` or `buildah bud .` in situations that they previously used docker without adjusting their configuration or code, checking docker hub (preferably first) needs to be the default configuration.

So, when you say things like "we're compatible with docker", how compatible? The impression of podman is that if you run `ln -s $(which podman) /usr/local/bin/docker` everything will continue working no problem.

(re: docker hub first: unexpected precedence of repositories is the root of https://www.bleepingcomputer.com/news/security/researcher-hacks-over-35-tech-firms-in-novel-supply-chain-attack/ )

**Comment by rhatdan** [comment]
Distributions choose the registries.conf to ship and as far as I know then all ship docker.io in the default list.  Containers/image needs to be registry agnostic. (Although it still has leaked in some docker.io.)

**Comment by rhatdan** [comment]
In Fedora we ship registries.conf in containers-common rpm, and it includes docker.io

grep docker.io /etc/containers/registries.conf
unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "registry.centos.org", "docker.io"]

**Comment by mtrmac** [comment]
containers/image quite intentionally does default to `docker.io/[library]` in the `docker://` transport; ambiguous/configurable short names were, for a long time, not a feature of c/image _at all_.

Now c/image does contain the shared “short names” implementation, and a `registries.conf` configuration file — but that does not just get used by Podman and installed automatically: the `podman` repo does not even contain the `registries.conf` file from c/image.

If an OS distribution or a container image uses `registries.conf` from this repository, that’s primarily because the creator of that OS made such a choice.

Yes, interoperability is very important, but by now there are two conflicting interoperability precedents (upstream Docker and the projectatomic/docker search behavior) and they can’t be satisfied simultaneously. Just like Fedora does, I would expect Podman distributors/packagers to ship a default configuration appropriate for their user base, regardless of c/image does.

That said, I wouldn’t reject a PR to edit the `registries.conf` contained in this repo to contain `unqualified-search-registries = ["docker.io"]` out of hand. Other co-maintainers might, I can’t speak of them. (I _would_ very fiercely reject a PR to edit the `registries.conf` contained in this repo to contain more than element in `unqualified-search-registries`, due to the ambiguity and security risk.)

**Comment by vrothberg** [comment]
In case the issue was motivated by recent updates of Podman 3.0 in the Kubic repos: that was a packaging bug.  It's entirely up to the distributions to decide which default registries they want.  Most distributions ship their specific registries (Fedora, CentOS, OpenSUSE, etc.) plus Docker.io at the end.

I am also open to set `unqualified-search-registries = ["docker.io"]` because it seems like a reasonable thing to do. @rhatdan WDYT?

**Comment by rhatdan** [comment]
I am not crazy about it, but I would not fight it.

**Comment by mtrmac** [comment]
Oh, I forgot about Kubic and OBS. Is that directly pulling the file from this repo?

Anyway, if nothing is _really automatically using_ `registries.conf` from here, and it exists purely as a template / recommendation, I’d prefer to keep it unset, to stand for the principle of “always qualify your references explicitly”. See above, AFAIK this file is not automatically included by vendoring, so not a part of Podman (and it’s only Podman we are discussing, aren’t we?).

**Comment by rhatdan** [comment]
Right this file is pulled into the containers-common package and then modified for each distribution.  The Podman packages we are involved with do not touch this file directly but do require containers-common, which ships a modified version of this file.

**Comment by AstraLuma** [comment]
I feel the need to point out that by putting docker.io at the end https://www.bleepingcomputer.com/news/security/researcher-hacks-over-35-tech-firms-in-novel-supply-chain-attack/ become trivially easy.

But I also didn't really expect this to go anywhere.

**Comment by mtrmac** [comment]
We do share the concerns about the search mechanism, and that’s why the defaults in this repository don’t invoke it.

I’m afraid this tracker is not the right place to argue for changing how Fedora, RHEL, or any other distribution decides to ship default configurations different from what this GitHub repo contains.
