### ISSUE TITLE
error parsing HTTP 401 response body: unexpected end of JSON input: ""

### ISSUE THREAD

**Issue by ipanova** [containers/image#1293]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

```
$ podman tag 6dbb9cc54074 namespace/i-have-no-perms-to
$ podman push  namespace/i-have-no-perms-to --log-level=debug
Getting image source signatures

DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] Checking /v2/namespace/i-have-no-perms-to/blobs/sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116 
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://auth.docker.io/token?scope=repository%3Anamespace%2Fi-have-no-perms-to%3Apull%2Cpush&service=registry.docker.io 
DEBU[0001] HEAD https://registry-1.docker.io/v2/namespace/i-have-no-perms-to/blobs/sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116 
DEBU[0001] ... not authorized                           
Error: error copying image to the remote destination: Error trying to reuse blob sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116 at destination: Error checking whether a blob sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116 exists in docker.io/namespace/i-have-no-perms-to: errors:
denied: requested access to the resource is denied
error parsing HTTP 401 response body: unexpected end of JSON input: ""

```

**Describe the results you received:**
error parsing HTTP 401 response body: unexpected end of JSON input: ""

**Describe the results you expected:**
HEAD request is issued to this endpoint ` https://registry-1.docker.io/v2/namespace/i-have-no-perms-to/blobs/sha256:b2d5eeeaba3a22b9b8aa97261957974a6bd65274ebd43e1d81d0a7b8b752b116`, which obviously does not contain response body. Client should be able to handle that and finish push operation without parsing errors

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.14.10
Built:        Tue Dec  8 14:37:43 2020
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 74feb474bea20d593dfb70e1e244893b9eb6b619'
  cpus: 2
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: example.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.6-300.fc32.x86_64
  linkmode: dynamic
  memFree: 1871626240
  memTotal: 4118777856
  ociRuntime:
    name: crun
    package: crun-0.17-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.2
  swapFree: 0
  swapTotal: 0
  uptime: 34m 35.25s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/vagrant/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/vagrant/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 15
  runRoot: /run/user/1000/containers
  volumePath: /home/vagrant/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438263
  BuiltTime: Tue Dec  8 14:37:43 2020
  GitCommit: ""
  GoVersion: go1.14.10
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc32.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mtrmac** [comment]
## The Immediate Cause

Example, with response dump:
```
DEBU[0003] GET https://auth.docker.io/token?scope=repository%3Ai-have-no-perms-for-x%2Fbusyboxdoesnoexist%3Apull%2Cpush&service=registry.docker.io 
DEBU[0003] HEAD https://registry-1.docker.io/v2/i-have-no-perms-for-x/busyboxdoesnoexist/blobs/sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b 
DEBU[0004] ... not authorized                           
ERRO[0004] ===RES===
HTTP/1.1 401 Unauthorized
Connection: close
Content-Length: 183
Content-Type: application/json
Date: Wed, 07 Jul 2021 16:46:46 GMT
Docker-Distribution-Api-Version: registry/2.0
Strict-Transport-Security: max-age=31536000
Www-Authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:i-have-no-perms-for-x/busyboxdoesnoexist:pull",error="insufficient_scope"


===RES=== 
FATA[0004] Error trying to reuse blob sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b at destination: Error checking whether a blob sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b exists in docker.io/i-have-no-perms-for-x/busyboxdoesnoexist: errors:
denied: requested access to the resource is denied
error parsing HTTP 401 response body: unexpected end of JSON input: "" 
```
and the presence of `WWW-Authenticate` means we end up at https://github.com/distribution/distribution/blob/01f589cf8726565aa3c5c053be12873bafedbedc/registry/client/errors.go#L123 , not a few lines below as I have speculated above.

## UI Intent

Note the `errors:\ndenied: …` text; the returned value is an `errcode.Errors` multi-error list, and this multi-valued reporting seems to be a sort of intentional design of distribution/distribution error reporting; compare https://github.com/containers/podman/issues/10858#issuecomment-874577933 also returning a two-value list.

The counterpart to this is how the Docker caller of that, at the top level (`TranslatePullError`) just returns the first element (recursively); which is why no-one has probably noticed till now.

## API Evolution

On the one hand the current value is clearly not useful and using “the most relevant” error would make sense, OTOH there are already callers checking for various docker/distribution typed errors (for good reason), so stripping data might break some of them.

Well, the most direct way to fix that is probably in the distribution/distribution error parser — and then update to the new repo from docker/distribution to distribution/distribution, which breaks callers’ type checks _just the same_. Sigh…

* If we are very strict about keeping c/image API, we can’t change any of this. Short-term Podman (libimage?) could recognize `errcode.Errors` and beautify that, without actually breaking the c/image API. 
* Technically, nothing _promises_ callers to return docker/distribution API types. So we _can_ change that, OTOH that’s also pretty certain to **silently** break some callers that check for those types, starting with our own c/common/pkg/retry. Updating the GitHub.com/containers ecosystem for the new types is the easy part; finding out who else needs to update would be harder.
* Another alternative is to break the callers this time again, and _also_ document the distribution/distribution types. I’m not much of a fan…
* Or break the callers this time again, explicitly document that distribution/distribution values are not an API promise (informative but not ultimately very useful) — and start defining our own error types the callers could rely on. OTOH taking on the _full_ error set would be a non-trivially big project, especially if the intent were to hide the various registry differences.

@vrothberg , others: WDYT?

**Comment by vrothberg** [comment]
Thanks for the wonderful summary, @mtrmac!

I am in favor of moving to distribution/distribution.  I just wanted to browse the repository and noticed that docker/distribution is now forwarding to distribution/distribution.  I could swear this was not the case two days ago, where I believe to have seen a "this repository is archived" banner.

Moving over to distribution/distribution and updating the containers ecosystem to me sounds like a good way forward.  We should also document that the values are not an API promise.  If needed we could selectively add some errors to c/image that would give promises.

**Comment by mtrmac** [comment]
FWIW #1299 will follow Docker in only reporting the first error from a multi-error list.

**Comment by ttys3** [comment]
I got lots of this: 

```
denied: requested access to the resource is denied
error parsing HTTP 401 response body: unexpected end of JSON input: ""
```

but I do have permission. retry again it works

**Comment by mtrmac** [comment]
Current failure text:
```
trying to reuse blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749 at destination: checking whether a blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749 exists in docker.io/namespace/i-have-no-perms-to: requested access to the resource is denied 
```

**Comment by davidesalerno** [comment]
I have the same @mtrmac's issue with podman and buildah inside a pod

**Comment by mtrmac** [comment]
@davidesalerno As noted above, at least the errors should no longer say “unexpected end of JSON input” in the originally-investigated scenarios.

If you still see that text with a recent version, please file a separate issue, with version numbers, the _full_ error message, and ideally a `--debug` / `--log-level=debug` log.

**Comment by MehdiSellamiAdministrator** [comment]
correctly according to the name of your docker hub repository.
