### ISSUE TITLE
The “human-readable description” returned by SetCredentials is wrong for a CredHelpers entry

### ISSUE THREAD

**Issue by mtrmac** [containers/image#1301]
It currently uses the return value of `modifyJSON`, i.e. the config file, not the helper.

**Comment by vrothberg** [comment]
https://github.com/containers/image/blob/main/pkg/docker/config/config.go#L98 suggests that non-auth-file helpers set the correct description.

I think we can close this one. @mtrmac, could you double-check to make sure I am not missing the point? This code hasn't changed much since the issue was opened.

**Comment by mtrmac** [comment]
Line 98 affects helpers set in `registries.conf`; those are indeed working as expected.

Consider https://github.com/containers/image/blob/8c27ca2070cc0837f4b5a0991562d09238cb9146/pkg/docker/config/config.go#L86 : the value of `desc` is set by `modifyJSON`, which is just the path, it doesn’t point at `auths.CredHelpers[key]`.
