### ISSUE TITLE
BoltDB reports errors by panic, which is passed through to callers

### ISSUE THREAD

**Issue by haircommander** [containers/image#1573]
There's a BZ https://bugzilla.redhat.com/show_bug.cgi?id=2089820 that encountered a panic in boltdb with the blobinfocache. Speaking to @nalind about it, he mentioned we probably could catch a panic and delete the file. This issue is to discuss and track that endeavor

**Comment by mtrmac** [comment]
There are various reports in the upstream repo, e.g. https://github.com/etcd-io/bbolt/issues/135 . Handling the error in another way was not discussed AFAICT.

**Comment by haircommander** [comment]
from what I can see in the bug, it looks like a disk corruption. they ran `fsck` and did some remediation but this was the result. I am not super convinced that catching the panic and removing the file is the most idiomatic approach, but it sounds like the panic is expected from bolt's perspective, and we can provide a slightly kinder UI for cri-o for these sitatuions. that said, it's rare, so if it's not worth the extra code, I'd understand and relay that back to them.

**Comment by mtrmac** [comment]
Conceptually, it would make much more sense to me to change the database, vaguely like this:

[boltdb.patch.txt](https://github.com/containers/image/files/8872980/boltdb.patch.txt)

But
- I don’t know at all what I am doing in that codebase
- To an extent, this is somewhat pointless (e.g. failures on rollbacks… can’t be recovered from, at least not _this_ way)
- There are _many_ other `panic` commands in the codebase.
- I can’t currently pursue this any further than this minimal proof of concept, which just demonstrates that the call stack of this particular panic is not _that_ wide.

---

The higher-level questions I have:
- Is this an unfixable corruption situation, like destroying a top-level data structure necessary to interpret the other data? Something that could, in principle, be automatically recovered from? Or perhaps just a bug in the codebase that “only” needs to be found and fixed? Answering this would require an expert in the codebase, _and_ a sample of the corrupt file, and I don’t think we have the latter.
- If this can happen for the other databases, are there any possibly not fully automated recovery tools (fsck-like) that users could use? (Or is it unnecessary because we would tell them to just blow away the node and redeploy?) https://github.com/etcd-io/bbolt/blob/master/cmd/bbolt/main.go is where I’d be looking for such a functionality, and it doesn’t look like there’s much there.

**Comment by mtrmac** [comment]
This will be resolved by stopping to use BoltDB, in #2092 .

**Comment by mtrmac** [comment]
Well, “resolved”; for API compatibility, `pkg/blobinfocache/boltdb` will continue to exist. But I’m not aware of any external callers.
