### ISSUE TITLE
types.BlobInfo is basically a Descriptor

### ISSUE THREAD

**Issue by runcom** [containers/image#164]
https://github.com/opencontainers/image-spec/blob/master/specs-go/v1/descriptor.go

@mtrmac wdyt?

**Comment by mtrmac** [comment]
The philosophical question is to what extent this is a generic concept and to what extent it is an implementation detail of a specific transport mechanism which should not be strongly coupled to the generic interface.

See the URLs discussion in #147, is that a plausibly generic field? When we are not using the field, are we “really” using the `Descriptor`?

Does moving to a `Descriptor` make anything easier in the code?

(This is _not_ a “no”, and using third-party code instead of maintaining it ourselves is generally attractive. It’s just not entirely clear to me what the fit is like.)

**Comment by mtrmac** [comment]
> When we are not using the field, are we “really” using the `Descriptor`?

My bad, #147 does actually add it.

**Comment by rhatdan** [comment]
@runcom @mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
I'll take a shot and close it. Replacing BlobInfo with something else seems like a scary rabbit hole to me.

**Comment by mtrmac** [comment]
Yeah, `BlobInfo` is a part of the internal API of `GetBlob`/`PutBlob`, which have been surprisingly in flux recently. Tying that to a vendor-neutral format specification would not make anything better.
