### ISSUE TITLE
OCI to docker:// fails with weird conversion error

### ISSUE THREAD

**Issue by cyphar** [containers/image#168]
If you try to use skopeo to push an OCI image to a Docker registry you get the weird error (this was done after copying the current `master` of `containers/image` to the `vendor/` of `skopeo):

```
% skopeo copy oci:opensuse:new docker://cyphar/opensuse_playground:latest
Getting image source signatures
Copying blob sha256:467db25190688bc9dc1d5fd6dbced1ac56f55d93a942987f448e62ad2614e46e
 46.97 MB / 46.97 MB [=========================================================]k
Copying blob sha256:eb9108dbdabef43ae694b955990153159c1cbd069c3e4ca5ac9ccdbdda0e4b09
 23.48 MB / 23.48 MB [=========================================================]
FATA[1275] Error creating an updated image manifest: Conversion of image manifest from application/vnd.docker.distribution.manifest.v2+json to application/vnd.docker.distribution.manifest.v2+json is not implemented
```

So it's failing to convert from itself to itself?

**Comment by runcom** [comment]
Ping @mtrmac

**Comment by cyphar** [comment]
I've made a patch in #169. However, I feel like the actual issue is that `oci:` -> `docker:` appears to convert the OCI configuration to a Docker Schema 2, but then it doesn't clear the mimetype so the `docker:` transport tries to convert it _again_.

**Comment by mtrmac** [comment]
WRT the confusing error message,
`FATA[1275] Error creating an updated image manifest: Conversion of image manifest from application/vnd.docker.distribution.manifest.v2+json to application/vnd.docker.distribution.manifest.v2+json is not implemented`

This is “conversion from $hardcoded to $requested”, and $requested is determined by `copy.go:determineManifestConversion”, which knows the true OCI type of the input instead of the cheating `manifestInstaceFromBlob` does.

And yes, the OCI→schema2 conversion needs to be implemented.

**Comment by cyphar** [comment]
This will be handled in #172 (#171).
