### ISSUE TITLE
docker-daemon -> OCI doesn't gzip layers

### ISSUE THREAD

**Issue by cyphar** [containers/image#178]
If you do something like:

```
% skopeo copy docker-daemon:opensuse/amd64:tumbleweed oci:opensuse:latest
Getting image source signatures
Copying blob sha256:bed80e2cbdd7d22d83fb2b743713df956c59d5edbfded661eda52e346ceed553
 150.50 MB / 150.50 MB [=======================================================]
Copying config sha256:0bd5203d80dd7795a2eaf8873f60f50b7f916ad05a538db489c4e60190e7121c
 1.73 KB / 1.73 KB [===========================================================]
Writing manifest to image destination
Storing signatures
% file opensuse/blobs/sha256/*
opensuse/blobs/sha256/0bd5203d80dd7795a2eaf8873f60f50b7f916ad05a538db489c4e60190e7121c: ASCII text, with very long lines, with no line terminators
opensuse/blobs/sha256/527ad855882abe493134cc4ffb282c020e13bb94a08f708003781d11d6eb5130: ASCII text, with very long lines, with no line terminators
opensuse/blobs/sha256/bed80e2cbdd7d22d83fb2b743713df956c59d5edbfded661eda52e346ceed553: POSIX tar archive
```

Which is wrong.

**Comment by runcom** [comment]
Should we have a gzip routine in OCI dest which detect if a layer is not gzip compressed and impress it? Right now in the docker save oci images PR upstream I compress the layer prior to being tarred up, so, it makes sense we would have  something in the OCI destination to automatically do this. @mtrmac wdyt?

**Comment by runcom** [comment]
In the upstream docker PR I wanted to say: I compress the layers prior to being passed to `PutBlob` (sorry I'm on a mobile phone)

**Comment by jonboulle** [comment]
Driveby - I really think we should just add the uncompressed types to the
OCI spec (there are a couple of open PRs along this line)

Antonio Murdaca <notifications@github.com> schrieb am Fr., 2. Dez. 2016,
11:17:

**Comment by runcom** [comment]
@jonboulle sgtm as well

**Comment by mtrmac** [comment]
Well, there are really two issues here:

- The MIME types in the container ecosystem are a mess (`gzip` MIME types actually autodetect uncompressed/gzip/bzip2/xz, at least in the Docker implementation; we use a special MIME type to mark “not distributable” which is not a type of the content at all). That’s mostly out of scope of this report; I would be happy if anybody cleaned that up but I suspect that backward compatibility concerns would make that difficult.

- Should the local-directory OCI be compressed? The current implementation does not, by analogy with `dir:`, because we assume that storage is cheap and the locally-stored data would likely be uncompressed soon.  OTOH, looking at https://github.com/opencontainers/image-spec/blob/master/layer.md , the OCI spec does say it “MUST” be compressed with gzip, so I guess we should switch.

> Should we have a gzip routine in OCI dest which detect if a layer is not gzip compressed and impress it? 

Not necessary, just change `ociImageDestination.ShouldCompressLayers` to return `true` and `copy.Image` will take care of that—_unless_ the image has signatures, in which case we don’t modify the layers, and are in violation of that `MUST`. But that’s not a concern for the `docker-daemon:`→`oci:` copy at least.

Eventually we might want to implement this aspect of OCI, starting with modifying `ShouldCompressLayers` to return “no”/“yes if possible”/“always”, and `copy.Image` would then either abort or drop the signatures. And I guess we should also worry about xz-compressed layers on input, which should be decompressed and recompressed using gzip.

For now, just flipping `ShouldCompressLayers` gets us 90% of what we want I guess.

**Comment by runcom** [comment]
> Not necessary, just change ociImageDestination.ShouldCompressLayers to return true and copy.Image will take care of that

mmm I was more talking about `PutBlob` rather than `copy.Image` - because in docker/docker we're using the image destination directly (not going through `copy.Image`.

**Comment by mtrmac** [comment]
> mmm I was more talking about `PutBlob` rather than `copy.Image` - because in docker/docker we're using the image destination directly (not going through `copy.Image`.

That is an option, sure, but it seems to be a bad match. If, as is in the case of OCI, the manifest schema dictates what the blob format should be, and the same manifest schema can be used in various transports, then the compression decision should be in the hands of `copy` or perhaps `image.genericManifest`, not in the hands of the individual transports.

For Docker, I guess this would mean using their own `distribution.compress` or something like that. (Also, full disclosure, sooner or later I will rip out the inline conversion from `ociDestination` and move it into `manifest_schema2.go, which will impact docker/docker).
