### ISSUE TITLE
Use k8s client library

### ISSUE THREAD

**Issue by aweiteka** [containers/image#188]
We need to extend our custom client to sign images from inside a build pod:

* Use env vars **KUBERNETES_SERVICE_HOST** and **KUBERNETES_SERVICE_PORT**
* Use token from `/var/run/secrets/kubernetes.io/serviceaccount/token`
* Use CA from `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
* Use namespace `/var/run/secrets/kubernetes.io/serviceaccount/namespace`

Our [openshift client](/containers/image/blob/master/openshift/openshift-copies.go) is a custom client. It would be much better to use the upstream [k8s client](http://kubernetes.io/docs/user-guide/accessing-the-cluster/#programmatic-access-to-the-api). This shouldn't significantly increase the size of the project.

**Comment by mtrmac** [comment]
I would dearly love to get rid of those 1000 lines; but using the OpenShift client did increase the size of the binary, by at least 50 MB if I remember correctly.

(That was an OpenShift client, using the OpenShift object types for the images etc, not a k8s client, though; perhaps that is something else entirely. It has also been more than 6 months since the original work, things might have changed.)

**Comment by aweiteka** [comment]
Basic testing looks like using the k8s go-client adds 45MB.

```
$ ls -lh skopeo
-rwxr-xr-x. 1 root root 18M Jan 12 15:19 skopeo
$ ls -lh skopeo.kubeclient
-rwxr-xr-x. 1 root root 63M Jan 12 15:17 skopeo.kubeclient
```

**Comment by rhatdan** [comment]
@aweiteka  @mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
Let's close it. Feel free to reopen if the issue gets revived.
