### ISSUE TITLE
`NewImage` does not fallback to other registries if image is not fully readable from a mirror

### ISSUE THREAD

**Issue by saschagrunert** [containers/image#2038]
Assuming we have the following `registries.conf`:

```toml
[[registry]]
  prefix = ""
  location = "registry.redhat.io"

  [[registry.mirror]]
    location = "brew.registry.redhat.io"
    pull-from-mirror = "digest-only"
```

Then a pull of 

```
registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:b1dcc377a56d26dd0fc4fc360b45b515f5cf8b368f5f81540f5f047447d17fec
```

Will not retry the fallback registry `registry.redhat.io`, if the digest is not found on `brew.registry.redhat.io`.

#### Error message

```
FATA[0000] pulling image: 
  rpc error: code = Unknown
  desc = fetching target platform image selected from manifest list: 
    reading manifest sha256:1941f88bcd73332cba3f794ee2dd3815a2255c9adfbbab4d4aa71f1710e2f614 in brew.registry.redhat.io/openshift4/ose-kube-rbac-proxy:
      name unknown: Digest not found
```
#### Investigation

The error here:

https://github.com/containers/image/blob/eedacf898ee41224372c6e9d5ba0cbf9a99e5341/internal/image/docker_list.go#L22

gets returned from `image.FromSource` (L34) in:

https://github.com/containers/image/blob/eedacf898ee41224372c6e9d5ba0cbf9a99e5341/docker/docker_image.go#L29-L39

but the registry mirrors are being tried in `newImageSource` (L30) before:

https://github.com/containers/image/blob/eedacf898ee41224372c6e9d5ba0cbf9a99e5341/docker/docker_image_src.go#L85-L94

Do we have to extend `newImageSourceAttempt` to further lookup the manifest (list) + digests being available on the registry? I guess this is a rare corner case of `brew.registry.redhat.io` being not a complete mirror of `registry.redhat.io`.

Refers to https://issues.redhat.com/browse/OCPBUGS-15778

**Comment by mtrmac** [comment]
Thanks for your report.

This is working as designed. Checking more is _not unreasonable_, but I think consistently going down the road of `newImageSourceAttempt` verifying that the image is “consumable” leads to pulling all of the 100GB image to verify that that all layers are present, and do not contain bit errors. And I think that outcome is clearly unreasonable.

The mirroring code is intended to fall back when the registry is down, or when an image is is not mirrored. It’s not nearly smart enough to be a general error mitigation strategy for all possible registry errors.

---

That “smart enough” code would probably mean not just choosing a mirror in `NewImageSource`, but creating a “multi-backend source” that can try all of the registries. And probably contacting the registry that worked for the previous operation. And remembering which registries are completely unreachable and result in a minutes-long timeout, and only trying those as a very last resort, so that every single operation is not slowed down (but yes, trying them again, in some situations). And doing all of that in a multi-threaded code, due to `HasThreadSafeGetBlob`. And possibly some interaction with retry logic, both with the lower-level logic in `bodyReader`, and at least non-interference with high-level retries at the CRI-O/Kubelet level.

It’s clearly not impossible to build such a thing. But it’s a Project.

Motivating that initiative with a rare obscure failure of this kind seems to me to be a bit of a stretch right now. OTOH that calculation might well change if sparse multi-arch images become more prevalent, and I can easily imagine that becoming true.

**Comment by saschagrunert** [comment]
Thank you for the clarification, closing this as-is.

**Comment by mtrmac** [comment]
>  OTOH that calculation might well change if sparse multi-arch images become more prevalent, and I can easily imagine that becoming true.

For the record, in that case really should consider what this PR suggests, and doing some kind of fallback _only_ on partial manifests (although it’s not immediately clear to me what that would look like, `NewImageSource` doesn’t know what the caller will ask for), and not going down the extreme path of ensuring blob correctness.

**Comment by mtrmac** [comment]
… and not starting the Big Project of multi-backend sources.
