### ISSUE TITLE
support for url path's in registries.conf unqualified-search-registries

### ISSUE THREAD

**Issue by AnthonyPoschen** [containers/image#2149]
Looking for support to be able to point unqualified search registries to an internal harbor proxy cache with the presumption all images missing a FQDN will be dockerhub based images

without having to make an alias for everything people consume we would like to be able to have the following configuration not spit out an error

unqualified-search-registries = ["harbor.mycompany.com/public-cache/library"]

and have the above path component act as a prefix to the images so for "nginx" the image lookup would become

harbor.mycompany.com/public-cache/library/nginx

**Comment by mtrmac** [comment]
In general, search registries are ambiguous and a security risk, and I’m rather opposed to expanding that feature.

Luckily, if there is a single registry, that’s not really a search.

> with the presumption all images missing a FQDN will be dockerhub based images

Doesn’t a single mirror, pointing `docker.io/library` to `harbor.mycompany.com/public-cache-library` (possibly along with `unqualified-search-registries` set to `docker.io`), do what you need?

**Comment by AnthonyPoschen** [comment]
I will have a test of  that idea @mtrmac and provide feedback. its 7pm local time so will most likely be tomorrow.

the context behind this request incase it helps is that i am setting up gitlab runners for a corporation and have full control of the environment and will be injecting the configuration files as read only files into the builds and we have the environment air gapped from the internet.

With that in mind we wanted to keep things as simple as possible for developer convenience, so its very common sadly to source internet images directly where it may use an image such as "alpine:latest". As every build job defined in a gitlab pipeline spawns a pod in kubernetes with the requested image we rewrite all images to internal proxy caches with an admission controller, so no FQDN is dockerhub, quay.io becomes harbor.../quay-cache, etc  all remappings we do is printed at the start of the job logs so they know the actual source image we started the build with. 

We wanted to extend that same functionality into the container build process so for the developer it feels seamless and they never need to refer to our internal proxy cache's for images from any provider thus making their "FROM ..." lines in dockerfiles more familiar and easier for any new developer to the business by just using what you would from home for a personal project. The company also has a lot of bad practices from using bamboo with open internet so this also aids in making the transition seamless as people can keep defining internet images while giving more security on our end now that we took away the direct internet access as they move over.

Some future planning would be to raise low / medium issues with anyone not using the correct image registries to ensure the slow transition off using the internet names for images.

**Comment by mtrmac** [comment]
My recommended final state (which may not be easily achievable, admittedly):
- All user-maintained files which point to images (e.g. includes `Containerfile`, K8s `Pod` / `Deployment` objects) contain a registry-qualified reference of _the canonical_ identity, regardless of location. So if the image “originally exists” at `quay.io/vendor/product`, then the config files should say `quay.io/vendor/product`. No short names, no ambiguity. (This does not rule out saying that “the canonical identity” is `my-project-registry.company.example/nginx`, and in the extreme `my-project-registry.company.example` might not even physically exist. Notably having the concept of a “canonical identity” then allows signing images using that canonical identity, and signatures don’t break/need updating when mirrored.
- Proxy caches, internet-isolated deployments, and the like, use the `registries.conf` mirroring support to redirect those canonical names to a physical registry, as necessary. It is possible, in `registries.conf`, to set the primary location as “blocked”, so that e.g. references to `docker.io` work but the `docker.io` registry is never contacted.

This works best if the mirroring configuration can be expressed using a small number of entries, ideally at the point of a whole registry (`docker.io` → `local-registry.example/docker.io`; `quay.io/only-quay-vendor` → `local-registry.example/that-quay-vendor`, and the like). Doing it one repo at a time is possible but quickly gets unwieldy.

**Comment by AnthonyPoschen** [comment]
I do agree that is the ideal final state and i don't think it is to unachievable it will just have the following issue.

Many / Most / A lot of developers are "low maturity" when it comes to containers, they aren't even thinking about "containers" or understand how they work properly they just understand "docker" and for these people the image originally exists as the short name as that is the only way they have ever seen them used. So the expectation from them will be when no FQDN is used it "just works like it does on my machine with docker desktop". Hopefully that mindset will change more as people are moving away from the bad practice docker introduced with images. But for now its a sad reality and I am trying to navigate it.

Thankfully for a CI/CD system only a handful of images should ever be commonly used and alias's can save the day. If your suggestion works ill paste the configuration in here for reference for anyone else coming across this topic and seeing as it would be a common issue for companies moving way from "docker" might be worth noting the pattern in the comments of registries.conf to aid other business's moving forward.

**Comment by mtrmac** [comment]
> Thankfully for a CI/CD system only a handful of images should ever be commonly used and alias's can save the day. 

Oh, yes; I completely forgot about `registries.conf` aliases. If you want to manage the image set used by developers, distributing an alias file is a pretty practical compromise. (A downside compared to using fully-qualified names in user-managed files is that user-managed files that require an alias file might conflict with other user-managed files that require some _other_ alias file. That’s more likely to come up when combining work of very separate teams, or possibly some external vendor’s software.)

**Comment by rhatdan** [comment]
Seems to be more of discussion then something that will be changed, so closing issue.  Feel free to continue conversation here.
