### ISSUE TITLE
proposal: Support append images into docker archive

### ISSUE THREAD

**Issue by STARRY-S** [containers/image#2231]
Currently, skopeo does not support appending images to the existing docker archive:

```console
$ skopeo copy docker://alpine:3.2 docker-archive:./test.tar
FATA[0000] initializing destination docker-archive:./test.tar: docker-archive doesn't support modifying existing images
``` 

Can we add appending new images to the existing docker archive file support?
Related code position: https://github.com/containers/image/blob/main/docker/archive/writer.go#L52

**Comment by mtrmac** [comment]
For the record, there is no way to do that by “appending”, because a tar file ends with and “end of file” marker. There is also a “manifest” file in the tar archive, which would need to be replaced. So we are looking at a complete copy+rewrite of the tar file to add a new image.

As always, consider `docker-archive:` a compatiblity/interoperability mechanism, it’s way too inefficient to be a part of any other workflows, and a registry server should be used instead.
