### ISSUE TITLE
Why do we get the whole image when inspect with docker daemon?

### ISSUE THREAD

**Issue by PMExtra** [containers/image#2429]
When I called

```Bash
skopeo inspect --daemon-host http://a.remote.host docker-daemon:foo:bar
```

it will send a request to the [export an image](https://docs.docker.com/engine/api/v1.45/#tag/Image/operation/ImageGet) API (`/images/foo/bar/get`) which transfers the whole image tarball to the client.

But I think the [inspect an image](https://docs.docker.com/engine/api/v1.45/#tag/Image/operation/ImageInspect) API is enough. It will save lots of traffic.

**Comment by mtrmac** [comment]
Thanks for reaching out.

The c/image abstraction design does not have an extra “inspect” API. There’s a “get manifest”, and the way `docker-daemon:` is implemented, that triggers a full, and costly, load and conversion.

`docker-daemon:` is a transition/compatibility mechanism for moving images to Podman, or to connect Docker’s storage with the c/image conversion pipeline. It not a full-featured client to the Docker Engine API, and due to the inherent serial nature of the export/import APIs, it’s also _never_ going to be as fast as using images in other locations. There’s not that much point in spending a lot of effort to optimize individual aspects of that, it could still not become be as fast as more native alternatives.

**Comment by PMExtra** [comment]
Thank you for your explanation. Now I understand why this design was chosen. I will consider using both Skopeo and docker-cli to achieve my goals.
