### ISSUE TITLE
Use godeps or glide for dependecy management 

### ISSUE THREAD

**Issue by hferentschik** [containers/image#269]
To make it easier for other applications to use _image_ as a dependency, it really should support at least one of the main package managers. Right now, if one specifies github.com/containers/image as a dependency using Glide, one ends up with multiple compilation errors. Given that the vendored dependencies are not checked in, there is not way for Glide to determine the set of dependencies.

One needs first find _vendor.conf_ and then manually add required dependencies.

**Comment by runcom** [comment]
nope, image is a library, it shouldn't matter if we're using vndr or anything else, there shouldn't be any deps in this repo - if there are, it's just because of testing and that shouldn't impact users of the library (I've imported image in many repos with Glide/Godeps w/o any issue). Not sure what's wrong with your setup.

**Comment by runcom** [comment]
oh, and no please, we're not going to change vendoring tool again :*(

**Comment by hferentschik** [comment]
> there shouldn't be any deps in this repo

+100, dependencies should not be checked in. 

> I've imported image in many repos with Glide/Godeps w/o any issue

Interesting. It did not work for me. In particular docker/docker/client was problematic and in the end I had to add more of the dependencies from _vendor.conf_. I will try to re-produce issue and add the error I get when just adding _image_ as a dependency.

**Comment by runcom** [comment]
@hferentschik we don't use `trash`, we use [`vndr`](https://github.com/LK4D4/vndr)

**Comment by hferentschik** [comment]
@runcom I am confused, so what's this then:

* https://github.com/containers/image/blob/master/Makefile#L20
* https://github.com/containers/image/blob/master/Makefile#L24

**Comment by hferentschik** [comment]
For what it's worth, there is a pull request for Glide to support rancher/trash - https://github.com/containers/image/issues/269

**Comment by mtrmac** [comment]
@runcom containers/image was modified in #244 to use `trash`; `skopeo` does use `vndr`.

**Comment by mtrmac** [comment]
> there shouldn't be any deps in this repo

To make this explicit, painful past experience shows that `vendor`ed dependencies are often unusable from callers of a library because Go treats them as separate = incompatible package names. (I suppose it could work for some entirely internal dependencies.)

So, the user of containers/image will need to somehow vendor the needed dependencies in the right versions, as recorded by our `vendor.conf`, or possibly some different versions to reconcile requirements of other used libraries. The provided `vendor.conf` is supposed to help with that work, but until Go has a standard dependency manager (which is, AFAIK, not yet the case), there will always be other tools, and manually supporting several is not really practical.

(Though, perhaps the formats could be automatically converted from one master source, if the tools are conceptually similar enough, and someone cared to automate this.)

**Comment by hferentschik** [comment]
Glide does provide the same functionality but is imo more popular. I would be happy to help switching to Glide, but if there is no interest feel free to close this issue.

**Comment by rhatdan** [comment]
@vrothberg is actually working on this with go modules, correct?

**Comment by vrothberg** [comment]
`go mod` is coming and we can't hide :) Let's close it.
