### ISSUE TITLE
integration tests? or better API for mocks

### ISSUE THREAD

**Issue by runcom** [containers/image#29]
we need something to exercise the various source and destination somehow (except directory) here in containers/image

**Comment by runcom** [comment]
maybe not, we need better mocks

**Comment by mtrmac** [comment]
Can we get away with having integration tests against real/live servers only in `skopeo`, per #27 ? Otherwise we are at high risk of writing and updating exactly the same tests twice, once using the CLI and once using the API.

Local server-less unit tests would still be useful, of course. An 80%, mock-less, solution, would be to split the send HTTP request+parse response methods into

 - “prepare HTTP request” helper
 - “parse HTTP response” helper
 - top level which calls the prepare helper, executes the request, and calls the parse helper.

Then we could trivially unit-test the two helpers with no IO (and the top level would remain not unit-tested). (I’m sure there is a fancy name for this pattern but I can’t recall right now.)

**Comment by rhatdan** [comment]
@runcom @mtrmac @vrothberg What is the state of this issue. It is two years old, can we close it?

**Comment by vrothberg** [comment]
I think this issue is fixed.

**Comment by mtrmac** [comment]
New contributors are really baffled by `make test-skopeo`; moving the integration tests directly into this repository would be nice. But I suppose that’s different from this “have _some_ tests at all” issue.
