### ISSUE TITLE
Rename signature transport type labels

### ISSUE THREAD

**Issue by aweiteka** [containers/image#304]
I understand the original justification for using these terms but the **atomic** and **docker** transport type labels are seriously misleading to users.

* why is the openshift API called "atomic"?
* why is a file- or http-based transport called "docker"?

Proposal:

atomic -> openshift
docker -> { urischeme | uri | scheme | http | file | ??? }

I'm assuming we could continue support for both old and new while deprecating. @mtrmac possible?

cc @rhatdan

**Comment by mtrmac** [comment]
Historically, `atomic` because of the stand-alone Atomic Registry idea. Nowadays I wouldn’t bother with that transport at all, #255 makes using `docker:` more convenient even for OpenShift servers. Let’s let `atomic`/`openshift` specifics die.

`docker` is named like that both for the precent CLI, and because the docker/distribution repo defines the [API](https://github.com/docker/distribution/blob/master/docs/spec/api.md); it’s not a _generic_ HTTP scheme that `http` would be appropriate [and saying `uri` in an URI does not mean anything at all]. I can understand the desire to avoid the name, but unless we actually fork the protocol, any name which does not refer to the docker/distribution repo, or the “Docker Registry” API as it calls itself, would be inaccurate.

(Supporting both is plausible but a bit tricky; e.g. what happens when the policy contains sections for both names of the transport? What happens with an older version of `atomic` or a similar tool which understands the old name but not the new one?)

**Comment by rhatdan** [comment]
I think this issue is dead, we should no longer use the term atomic.

**Comment by mtrmac** [comment]
Yes; eventually, the OCI distribution specification may motivate using another name, but not right now.
