### ISSUE TITLE
oci transport will remove existing images

### ISSUE THREAD

**Issue by cyphar** [containers/image#306]
If you try to have a multi-tag image with `skopeo` (by copying to different tags), then it will delete old tags. I also have a feeling that manifests without tags will be _really_ broken. You can verify this fairly trivially by doing:

```
% skopeo copy docker://opensuse/amd64:42.2 oci:opensuse:latest
% skopeo copy docker://opensuse/amd64:42.1 oci:opensuse:42.1
% jq . opensuse/index.json
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:6842a022e2395f4d03350f5917908b4efc1aa80c302990dc74a577ebd7df0bff",
      "size": 349,
      "annotations": {
        "org.opencontainers.image.ref.name": "42.1"
      },
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    }
  ]
}
```

I'll investigate this later. I found this while trying to increase umoci's testing.

**Comment by cyphar** [comment]
For reference, IMO this should be handled in a similar way to umoci's `oci/casext.UpdateReference` implementation.

**Comment by cyphar** [comment]
I believe this is related to projectatomic/skopeo#369.

**Comment by mtrmac** [comment]
I don’t think this is https://github.com/projectatomic/skopeo/issues/369 ; it’s just that `ociDestination.Commit` ignores any pre-existing index and overwrites it with a single-manifest index for the just written manifest. That’s not intentional, contributions to fix this would be welcome.

(Also discussed in https://github.com/containers/image/issues/155 .)

**Comment by rhatdan** [comment]
@mtrmac @cyphar Is this still an issue,  Just going through old issues and trying to clean them up.

**Comment by mtrmac** [comment]
This was fixed in https://github.com/containers/image/pull/326 ; when a tag is specified, only that image in the index is added/replaced without affecting other tags.  (When no tag is specified, it seems that the first untagged image or image with an empty tag is added/replaced.)

(Note that this does not allow multi-arch images, with the various architectures sharing a tag, yet; see #400 for some work in that direction.)
