### ISSUE TITLE
Digest verification not performed on manifests and other blobs

### ISSUE THREAD

**Issue by williammartin** [containers/image#343]
For OCI and Docker images, it seems we only verify the digest of the `ConfigBlob` (https://github.com/containers/image/blob/master/image/oci.go#L82-L85 + https://github.com/containers/image/blob/master/image/docker_schema2.go#L120-L123). It feels like this should occur for all blobs downloaded, instead of relying on every library consumer to remember, and to correctly implement verification of the blobs.

From what I can see this has been avoided because `GetBlob` returns a stream, and we let the consumer decide how to handle that stream. I'm wondering whether there is some work we can do, such as providing a `Reader` that wraps the `resp.Body`, verifying the digest on `EOF` and returning an error if the check fails?

**Comment by mtrmac** [comment]
The verification also happens for manifest digests in https://github.com/containers/image/blob/master/image/unparsed.go#L57 , and for blobs in https://github.com/containers/image/blob/master/copy/copy.go#L641 and other uses of `digestingReader`.

What are you ultimately trying to do? If the goal is to read the whole image, it might be better to call `copy.Image` instead of the individual `types.ImageSource` methods.  `types.ImageSource` is not responsible for this integrity verification mostly intentionally: it would be too easy for the transports go get out of sync, or for some transport to just forget. This way, transports only handle the data transport, and verification happens in the shared consumers.

_If_ `copy.Image` is a completely inapplicable, making something like `digestingReader`, and perhaps some other helper for manifest/config verification, public, seems reasonable. But I’d really recommend looking at `copy.Image` first.

**Comment by williammartin** [comment]
Oh wow, totally did not see this verification when I was searching. Let me look into it and get back to you. Thanks a lot.

**Comment by williammartin** [comment]
I'm gonna close this pending further investigation on our side, looks like a mistake from me! Thanks @mtrmac
