### ISSUE TITLE
Image -> ImageCloser confusion

### ISSUE THREAD

**Issue by williammartin** [containers/image#387]
This commit: https://github.com/containers/image/commit/32374d9fa917ee18bb6cffaca1946ee3e7217b37 broke us and I'm trying to figure out what the best resolution is.

The issue is that our flow is:

```
originalImage := reference.NewImage(...)
updatedImage := originalImage.UpdatedImage(...)
....
updatedImage.Close()
```

But now `types.Image` doesn't have a `Close()` method. Because of the way Updating is spread across image types, I'm not sure it's possible to assume all will have the right closers. Maybe @mtrmac you could talk about how you intended for people to deal with this use case idiomatically?

**Comment by mtrmac** [comment]
This should work
```go
originalImage := reference.NewImage(...)
updatedImage := originalImage.UpdatedImage(...)
…
// updatedImage.Close() // Was, strictly speaking, required in the old version, but memoryImage.Close is a no-op; should happen before originalImage.Close()
…
originalImage.Close() // This actually closes the ImageSource
```

---

The goal of that commit is to allow
```go
src := reference.NewImageSource(…)

img1 := image.FromUnparsedImage(ctx, image.UnparsedInstance(src, nil)) // == image.FromSource(ctx, src)
…
img2 := image.FromUnparsedImage(ctx, image.UnparsedInstance(src, archSpecificManifestDigest))
…
src.Close() // img1, img2 can no longer be used
```

like `copy.Image` does, where discarding a `types.Image` does not automatically close the underlying `types.ImageSource`.

(Ideally we should do better about enforcing the “closed” state of sources;  the ordering of `originalImage.Close`/`updatedImage.Close`/`src.Close` is currently not enforced/protected by the code, only documented, or not even that.)

Fairly often you might want to do the explicit `NewImageSource`/`UnparsedInstance` pair instead of `NewImage`:
- If the code wants to access both the metadata through `Image` and the underlying blobs through `ImageSource`, `NewImageSource`+`FromUnparsedImage(UnparsedInstance)` is more efficient than `ref.NewImageSource`+`ref.NewImage` (a tiny bit for `docker:`, a _lot_ for `docker-daemon:` and `oci-archive:`)
- As the commit says, `NewImage` is handling manifest lists in a quite surprising way, and manifest lists are now fairly widespread. It is OK to use `NewImage` to just parse some hopefully arch-invariant metadata, but e.g. when computing a manifest digest the caller should really make a conscious decision whether it should be a digest of the manifest list or the arch-specific manifest.

**Comment by williammartin** [comment]
Ok thanks for taking the time. I'll close this out as it was more of a question and will reopen if anything else comes up.
