### ISSUE TITLE
Enable overriding TemporaryDirectoryForBigFiles in runtime

### ISSUE THREAD

**Issue by jfilak** [containers/image#495]
I need to pull big images - hundreds of GBs. I don't want to mount  my containers related device to /var/tmp . I don't want to rebuild this project just to change the tmp directory.

Would it be possible to introduce an environment variable (e.g. CONTAINERS_IMAGE_TMP_DIR?) or a configuration option where I could specify the directory for big files?

**Comment by mtrmac** [comment]
Thanks for your report.

Sure, this makes sense; I’d generally prefer an explicit option via `types.SystemContext` to an environment variable.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg What is the state of this issue? Do we have a way of satisfying it?  Can I close the issue?

**Comment by vrothberg** [comment]
Nope, this is still open. Marking it as good first issue.

**Comment by jvanz** [comment]
I was reading the code of the `image` and `skopeo` to find the approach to add this feature. As far as I can see in the code the files using the `tmpdir` module does not have direct access to the `SystemContext`. Thus, if we want to have this data in the context we need to add an argument in the function arguments adding the `SystemContext`. But I am not sure if this is worth it. So, I decide to expose a function where the library user can override the config. Something like this: https://github.com/jvanz/image/commit/0028bc33234585140aae7dacf1d5c3c971b64769

What do you think?

**Comment by mtrmac** [comment]
No, c/image is a library and should, if at all possible, not have global state that affects unrelated users (that may not be aware of each other at all) like that.

`c/image/internal` is not visible from callers, so not a part of the API, and we are completely free to change it.

Most callers of `TemporaryDirectoryForBigFiles` do have, or can easily get, access to a `SystemContext`; the only outsider is `c/image/docker/tarfile… which should, arguably, be made private in the next major version.

**Comment by filak-sap** [comment]
Any progress? Our images are huge and I hesitate to bind mount my openstack volumes to `/var/tmp`.

**Comment by rhatdan** [comment]
podman 1.6.0 will default tmp operations to be in /var/tmp, no longer /tmp.

**Comment by filak-sap** [comment]
docker stores temporary data in /var/lib/docker/tmp, so I could easily provided enough disk space just for docker write temporary data.

podman writes temporary data to /var/tmp, but our OpenStack images have up to 64GB, so I need to provide additional disk space for /var/tmp

podman stores some data in /var/lib and some in /var/run.

One could say I should just mount a big volume to /var, but it's not possible to mount volumes before I create the VM from an image in our OpenStack - therefore, the mount would hide data in /var.

So I mount our volumes to /containers and I change runroot and graphroot to /containers/runroot and /containers/graphroot.

I cannot easily provide additional disk space for temporary data because if I bind mount new FS to /var/tmp, I hide the content already provided (I guess I could use OverlayFS but do I need to do such excercise?).

It would be cool, if I could configure also the temporary directory.

Shall I open a pull request?


PS: Our images starts with 45GB - we store data along with code (ABAP) in database (Database is our File system and also our Data storage) and there is no way we can separate them (because our database engines stores data in huge monolithic files including all tables).

**Comment by rhatdan** [comment]
Well that might be a better default then /var/tmp/  I think if we basically setup TMPDIR to point at the GraphRoot()/tmp dir, then the tools podman/buildah would put the storage in the correct location.

This would also solve your problem since you would just add storage to the graphroot.

**Comment by Zyqsempai** [comment]
Hey guys, is it still actual? Can I take this one?

**Comment by rhatdan** [comment]
@Zyqsempai Sure take a stab at it.

**Comment by rhatdan** [comment]
Buildah and Podman are using TMPDIR for this, and we want to tell users to set TMPDIR environment variable to a location that they want to store the data.  
Podman and Buildah can set this directory in Containers/image when we have a Function.
