### ISSUE TITLE
index.json file updated whichever last command it executed when destination for 2 or more images are same.

### ISSUE THREAD

**Issue by praveenkumar** [containers/image#513]
Does below is expected?

Run both command around same time and let both to be finished.
```
$ skopeo copy docker-daemon:fedora:latest oci:/home/prkumar/Downloads/image
Getting image source signatures
Copying blob sha256:108b1c56d076789d94323e2bcaa7eb926485f8fc841d6c08335f39412d94b71c
 251.75 MB / 251.75 MB [===================================================] 18s
Copying config sha256:8eb3fbe7fbad92f6cf4eccb9ad5010484f83af2c1d5781442e3a0dc6f537e8ca
 1.31 KB / 1.31 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

$ skopeo copy docker-daemon:busybox:latest oci:/home/prkumar/Downloads/image
Getting image source signatures
Copying blob sha256:8a788232037eaf17794408ff3df6b922a1aedf9ef8de36afdae3ed0b0381907b
 1.31 MB / 1.31 MB [========================================================] 0s
Copying config sha256:d98834fba17e4121dc21f65d6ddf2f648da119c86d72ffea8145e496bda621fd
 574 B / 574 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
```

Which ever command is finish last will have the content to index.json (not both) but blobs are present for both the images.

```
$ python -mjson.tool image/index.json 
{
    "manifests": [
        {
            "digest": "sha256:54bd85ff37b2abc82b8113c02af3bc14e77357f6ba136adfb2e0484cb4b2e9bb",
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            },
            "size": 350
        }
    ],
    "schemaVersion": 2
}

$ ls -l image/blobs/sha256/
total 85616
-rw-r--r--. 1 prkumar prkumar      350 Oct  9 12:53 54bd85ff37b2abc82b8113c02af3bc14e77357f6ba136adfb2e0484cb4b2e9bb
-rw-r--r--. 1 prkumar prkumar 86922341 Oct  9 12:53 565884f490d9ec697e519c57d55d09e268542ef2c1340fd63262751fa308f047
-rw-r--r--. 1 prkumar prkumar     1341 Oct  9 12:53 8eb3fbe7fbad92f6cf4eccb9ad5010484f83af2c1d5781442e3a0dc6f537e8ca
-rw-r--r--. 1 prkumar prkumar   727978 Oct  9 12:53 90e01955edcd85dac7985b72a8374545eac617ccdddcc992b732e43cd42534af
-rw-r--r--. 1 prkumar prkumar      347 Oct  9 12:53 b4f1424d3f12ec809dc268c6c87d25d8b3869813aea92c9dfaf7429de802030e
-rw-r--r--. 1 prkumar prkumar      574 Oct  9 12:53 d98834fba17e4121dc21f65d6ddf2f648da119c86d72ffea8145e496bda621fd
```

- Additional info - https://github.com/minishift/minishift/issues/2474

**Comment by mtrmac** [comment]
Yes; if the destination is `oci:`_directory_, it is interpreted as “an unnamed image in _directory_”, and subsequent copies overwrite the unnamed image entry.

You can use `oci:`_directory_`:`_nameAnnotation_ to store many different images in a single OCI repository, disambiguated by the _nameAnnotation_.  (See `org.opencontainers.image.ref.name` in https://github.com/opencontainers/image-spec/blob/master/annotations.md for the full syntax, it is a superset of Docker references.)

E.g.
```sh
skopeo copy docker://busybox:latest oci:ocidest:busybox:latest
```

**Comment by mtrmac** [comment]
FWIW https://github.com/minishift/minishift/issues/2474 seems unrelated: in that case, the code does seem to be using the `nameAnnotation` syntax, and experiencing a race in updating the file: between the time the manifest is read, updated, and written back, something else can read the old version, and then rewrite a different updated version which discards the first set of changes.

That race is, AFAICS, _fundamentally unfixable_, because the OCI format does not specify an interoperable locking mechanism. (File-based locks in POSIX could be used, but they are attached to inodes, not file names, so the popular create-temp-file+rename way of ensuring an atomic rewrite would AFAICS break the locking scheme.) E.g. the locking scheme for `/etc/passwd`, which uses file-based locks, is quite elaborate (requiring _two_ separate lock files, and writing PID numbers inside them), and using something like that without an OCI spec would again not be interoperable.

(Also, it’s not just the index; plausibly there could be one concurrent process uploading an image, relying on a pre-existing blob in the repository, and another concurrent process cleaning up unused blobs, and removing it just after the first process notices that it exists.)

I may well be missing an obvious solution here; but if I’m not, it seems to me that it unfortunately has to be the caller’s responsibility to ensure only one concurrent writer to an OCI repository.


We could decrease the race window by only reading the manifest (or re-reading it) immediately before the update+write, but that would make the races still possible, just harder to trigger. I’m honestly not sure which of the two behaviors is better—the current implementation at least makes the races fairly obvious and forces the callers to handle them earlier in the development cycle; shortening the race window would make them rarer but also much more difficult to notice and debug.

**Comment by praveenkumar** [comment]
> We could decrease the race window by only reading the manifest (or re-reading it) immediately before the update+write, but that would make the races still possible, just harder to trigger. I’m honestly not sure which of the two behaviors is better—the current implementation at least makes the races fairly obvious and forces the callers to handle them earlier in the development cycle; shortening the race window would make them rarer but also much more difficult to notice and debug.

@mtrmac I agree, we will spend some more time from minishift side how this can be resolved and this race condition might be fixed.

**Comment by mtrmac** [comment]
Apparently Minishift has avoided the race in containers/image index updates in https://github.com/minishift/minishift/pull/2874 — though not by adding locking, but by using an unique index location and manually reimplementing the update of the shared index (in exactly the same racy way, just with a shorter window, as discussed in 
https://github.com/containers/image/issues/513#issuecomment-428237673, and still with the same races WRT reading in-progress blob writes) 🙁

It still seems to me that there is no way this _can_ be fixed in c/image , and as long as Minishift is happy with its solution, I don’t know that there is anything else to do here.
