### ISSUE TITLE
Force signature version

### ISSUE THREAD

**Issue by cristi-** [containers/image#538]
Hi,
Could i configure docker to try only "signature-1" and not "signature-2" ? The problem we're having is that our signatures are stored in s3 and, when we run docker pull image, docker tries signature-2 first, resulting in a 403 returned from S3 and the request fails:
```
Trying to pull repository repostory:1443/namespace/image ...
repostory:1443/namespace/image:18.11.0.8 isn't allowed:
 Error reading signature from https://ztbucket-sigs-eu-west-1.s3-eu-west-1.amazonaws.com/namespace/image@sha256=3dcd966b0f13e3b266e5f8d38d8e928277878a4766ee9c9cb967461286e9f61f/signature-2: status 403
```

This can be temporarily fixed by setting the s3 bucket to public, but I was wondering if there's a way to force docker to search for signature-1 only. Or maybe there's a way for docker to try the second signature type even if the first returns 403?

Thank you!

**Comment by mtrmac** [comment]
Thanks for your report.

There may be an arbitrary number of signatures, and any single one (or all of them) may be required in order to conform to the configure policy; so just reading one is not, in general, sufficient. The code is designed to try signature-{1,2,3,…} until it gets a 404.

Is it impractical to configure the web server to return 404 status for missing files? It would be _technically possible_ to stop at a 403, but it’s not obviously the right thing to do.

**Comment by cristi-** [comment]
This issue is specific to how the s3 website storage resolves missing files, in private buckets, by replying with a 403 code. 
I thought maybe there was a way to specify a fixed version api for the signature. If this is by design then it's ok and I will recommend that we use a public s3 bucket which seems to work.
Thank you!

**Comment by rhatdan** [comment]
What registry are you using?

**Comment by cristi-** [comment]
We are using docker-distribution v2.6.2. The signatures are created with skopeo and synced to an S3 bucket.
