### ISSUE TITLE
Registry White Lists in registries.conf

### ISSUE THREAD

**Issue by adambkaplan** [containers/image#548]
Enhance `registries.conf` to support explicit registry white-lists. If white-listing is utilized, only images from the listed repositories are allowed to be pulled, pushed, and run.

Ideally implement similar behavior that was supported in OpenShift 3.x - see [OpenShift day two guide](https://docs.openshift.com/container-platform/3.11/day_two_guide/docker_tasks.html#docker-external-registries-whitelist-and-blacklist). Please note that `registries.search` should **not** be re-purposed to support white-list behavior.

**Comment by runcom** [comment]
@umohnani8 @QiWang19 PTAL

**Comment by vrothberg** [comment]
@runcom, I think we can apply a trick to make this work. The new prefix-based format of the `sysregistriesv2` package can be extended to support wildcards. So we could have something as follows (format is wrong but the idea should be clear):
```
registry-A:
prefix=*
blocked=true

registry-B:
prefix=my-trusted-registry.com:5000
```

The prefix matching will make sure that either registry-B is used and that anything else will be blocked.

But this would just be one of many nice features when adding wildcard-support.

@rhatdan WDYT?

**Comment by vrothberg** [comment]
A complementary statement to the idea above. It will work as always the registry with the longest prefix match will be selected.

**Comment by rhatdan** [comment]
My fear is having two ways of doing this is going to lead to confusion.  Which one wins.  If I reject everything in policy.json and I whitelist in registries.conf?

**Comment by runcom** [comment]
Trust and registry whitelisting are two separate and orthogonal thighs. Even if I whitelist a registry, it doesn't mean I trust images from that registry. Having people deal with trust as a mere mean to block certain registries is misleading and can lead to confusion as well.
The confusion can be made clear by well defining the purpose of both configuration, but using the trust one to configure blocking is misleading to me.

**Comment by adambkaplan** [comment]
I think an analogy with firewalls and SSL certs is helpful here. You can use a firewall to block IPs and domains en masse, as well as use CA's to trust/distrust a particular website.

**Comment by rhatdan** [comment]
Perhaps I am clueless,  I don't see the difference.  
Could someone give use cases based on podman commands where they would expect a difference.

**Comment by vrothberg** [comment]
> Perhaps I am clueless, I don't see the difference.
> Could someone give use cases based on podman commands where they would expect a difference.

A university environment is usually a good scenario. An admin may forbid accessing porn-container registries and trust all others but some internal staging registry.

**Comment by mtrmac** [comment]
The way I generally understand “whitelist”, it is a an alternative to a ”blacklist”, i.e. “somebody must explicitly put you on the whitelist for you to ‘pass’” vs. “anyone who is not explicitly added to the blacklist can ‘pass’ by default”.

That is _orthogonal_ to what “‘pass’ the list check” means. A hypothetical {black,white}list could in principle be set up either an independent check to signature enforcement (i.e. an image must pass _both_), or as an alternative (an image only needs to pass _one of them_).

Only the independent check (must pass both) approach matches the way I think – it allows considering each of these mechanisms independently, rather than having to always consider (in principle arbitrary) interactions between many mechanisms. But that does not mean that a computer can’t implement anything else — even a JavaScript policy language able to call these various implementations at will (/me \*shudder\*s at the thought of polkit).

---

It would, ideally, be best to go back to the underlying requirements behind the Docker black/whitelist mechanisms, _and the contexts in which they are used_. We could well find out that what the users actually need is an Ansible “assertion” feature, or something like that, and nothing at a node level.

I guess we are stuck with providing a compatibility mechanism for the current implementation / layering design, though, and trying to accommodate all workflows that have accumulated since.  In that case I prefer keeping the signature configuration and black/whitelist configurations orthogonal, to  make reasoning about them much simpler.

**Comment by rhatdan** [comment]
Ok lets go with the example of university wants to block access to 
porn.com

What does the admin do?
With policy.json he just executes

podman image trust -t reject porn.com

Now users can not pull from porn.com ( I guess this is a black list)

What do you see an admin doing with this new proposed "whitelist" where the admin wants to allow everything except porn.com?

**Comment by runcom** [comment]
I'm sure it would, I'm not against something easy, UI wise, like that. I'm just worried about using trust to block registries. The command above means "don't trust images from that registry, hence, avoid pulling them" whether we need something like "avoid pulling from that registry because I say so" even if the commands may overlap in practice

**Comment by rhatdan** [comment]
I don't care about the word trust.  If the use case is I only want my users to pull from
openshift.registry.company.com and if they pull from Docker.io, I want it blocked then the policy.json file satisfies this need.  

I don't see how adding something like whitelist/blacklist to registies.conf changes this?

If the goal is to allow user dwlash pull from anywhere while runcom can only pull from openshift.registry, then we have a different issue.

**Comment by vrothberg** [comment]
Thanks, @bparees, for adding those use cases! Scenario 2 is already working today by adding `bad.registry.com` to the list of *blocked* registries in the `registries.conf`.

In my opinion, those things should be configured in the `registries.conf` as I find it more user-friendly to have one config file for all/most things related to registries. Such behaviour could be achieved by adding a new config switch (e.g., `default_policy="reject_all"`). @mtrmac WDYT?

**Comment by bparees** [comment]
> In my opinion, those things should be configured in the registries.conf as I find it more user-friendly to have one config file for all/most things related to registries.

I agree.

> Such behaviour could be achieved by adding a new config switch

how do i implement scenario (1) in registries.conf?  where do i list the "allowed" registries in registries.conf?

**Comment by vrothberg** [comment]
> how do i implement scenario (1) in registries.conf? where do i list the "allowed" registries in registries.conf?

That doesn't work with registries.conf at the moment. If we want to support that we need an additional mechanism to configure the default_policy.

**Comment by bparees** [comment]
> That doesn't work with registries.conf at the moment. If we want to support that we need an additional mechanism to configure the default_policy.

even assuming we could configure the default_policy, what does the rest of the configuration look like?

**Comment by rhatdan** [comment]
I think we need to look at long term and short term.  In the short term we can handle use case 1 and 2 in policy.conf

Reject everything except registries.access.redhat.com
```
more /etc/containers/policy.json 
{
    "default": [
        {
            "type": "reject"
        }
    ],
    "transports": {
        "docker": {
            "registries.access.redhat.com": [
                {
                    "type": "insecureAcceptAnything"
                }
            ]
        }
    }
}
```

**Comment by rhatdan** [comment]
reject: bad.registry.com, allow: all # disallow pulling/pushing for some specific registries, allow others
```
# cat /etc/containers/policy.json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "bad.registry.com": [
                {
                    "type": "reject"
                }
            ]
        }
    }
}
```

**Comment by bparees** [comment]
thanks @rhatdan.  So that syntax is supported today?

**Comment by rhatdan** [comment]
Yes

**Comment by rhatdan** [comment]
podman image trust 
makes it easy to play with.

**Comment by rhatdan** [comment]
The third test is just depends on what you set for default.

**Comment by bparees** [comment]
```
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports": {
        "docker": {
            "bad.registry.com": [
                {
                    "type": "reject"
                }
            ]
        }
    }
}
```

Doesn't this also mean we'd treat all registries as insecure (ie allow invalid TLS certs + non-TLS transport?)

**Comment by rhatdan** [comment]
I think that it is handled in registries.conf.

**Comment by bparees** [comment]
I guess i am confused by `"type": "insecureAcceptAnything"`, that implies to me that it's going to accept insecure registries.

**Comment by rhatdan** [comment]
Basically it means, it does not require signatures.  We have a third option which would require signed images.

**Comment by bparees** [comment]
ok, so not related to TLS/transport.

**Comment by bparees** [comment]
@adambkaplan so it sounds like we should proceed in the following manner:

1) wire search registries -> registries.conf
2) wire insecure registries -> registries.conf
3) wire allowed/blocked registries -> policy.json in the way that @rhatdan outlined above.

sound good?

**Comment by adambkaplan** [comment]
@bparees sounds good to me.

@rhatdan can `policy.json` be encoded via a go type? I assume yes.

**Comment by rhatdan** [comment]
It is just simple json, so I see not reason why not.  Containers/image might do something with that now.  @vrothberg Do you know?

**Comment by nalind** [comment]
@adambkaplan it should be a `github.com/containers/image/signature.Policy`.  The package's tests include [an example](https://github.com/containers/image/blob/master/signature/policy_config_test.go#L232).

**Comment by adambkaplan** [comment]
Closing this issue, as `policy.json` is the better path forward for this capability.

**Comment by mtrmac** [comment]
> Such behaviour could be achieved by adding a new config switch (e.g., `default_policy="reject_all"`). @mtrmac WDYT?

What happens when `policy.json` contains a different default? It’s much simpler when such an ambiguity can’t happen and we don’t have to answer that question.

**Comment by mtrmac** [comment]
> 3. wire allowed/blocked registries -> policy.json in the way that @rhatdan outlined above.

If you want to do it this way, be _very_ careful about pre-existing data. `policy.json` is an OS-wide config file, not _in general_ something that is free for OpenShift to just overwrite (unless OpenShift “owns” the whole OS, of course).

It would be extremely bad to replace a `type: signedBy` policy entry (or, really, _any_ pre-existing entry) with a `type: insecureAcceptAnything` one. And make sure to handle the case of a >1-entry array defined for a scope.

Also, I think you’ll want to express the “block all non-whitelisted registries” in `"transports"."docker".""` (`docker://`-specific default), not in the global default (which would also impact references to images in local storage, `dir:` and everything else).

> @adambkaplan it should be a `github.com/containers/image/signature.Policy`. The package's tests include [an example](https://github.com/containers/image/blob/master/signature/policy_config_test.go#L232).

The API of that package is, right now, focused on evaluating the policy, and in programmatically creating the data structure, but quite a few of the underlying config fields are private. I.e. you can create a policy and/or parse it from JSON, and then either marshal it to JSON or _evaluate_ it.  OTOH if you want to load the policy and then make decisions based on its contents, you might find that the necessary data is private. (This was originally motivated a) by hoping to avoid making the less stable parts of the data a public API, and b) by … “encouraging” consumers to use the provided policy implementation instead of writing a parallel one.)

We might need to relax that, or \*shrug\* maybe use the other formulation recently added to `libpod/pkg/trust` (careful, not sure that it’s complete) which defined its own types instead of relaxing the c/image/signature ones (… at which point keeping the c/image/signature types private does not have that much of a point any more.)
