### ISSUE TITLE
docker transport always uses docker.io as the default registry

### ISSUE THREAD

**Issue by adambkaplan** [containers/image#572]
Image pulls which use the `docker` transport will default to using docker.io as the default registry, even if docker.io is not present in the `registries.search` config. This impacts buildah (and potentially podman).

**Steps to reproduce:**

1. Create a `registries.conf` file which does not include docker.io in the search path:
```
[registries]
[registries.search]
registries = ['quay.io']
```
2. Use buildah to pull an image without referencing a repository, using the conf file above:
```
$ buildah --registries-conf=paht/to/registries.conf pull busybox:latest
```
3. Create a simple Dockerfile from an image without a repository:
```
FROM busybox:latest
RUN echo "Hello!"

ENTRYPOINT ["/bin/bash"]
```
4. Run a buildah build using the Dockerfile above:
```
$ buildah --registries-conf=path/to/registries.conf bud -t myimage .
```

**Expected behavior:**

`buildah pull` should fail (image does not exist on quay.io, and docker.io is not on the search path).

**Actual behavior:**

Pull succeeds, but `buildah bud` fails trying to locate the image.

**Comment by mtrmac** [comment]
Thanks for your report.

The c/image/docker transport (which backs the `docker://` syntax) uses the traditional `docker.io/library` normalization, that is expected behavior.

The transport does not _at all_ support `registries.search`; c/image does provide `c/image/pkg/sysregistries*` subpackages that allow parsing that configuration, but it is _never_ interpreted in this library, notably because supporting the search semantics breaks signatures (we need _explicit user input_ to say which image was intended to pull, so that we can match the signature against the right public key and the right image identity).

That search semantics has always been supported, if at all, by Buildah and Podman themselves, and unless someone proposes a way to integrate search with signatures in a consistent way, it must stay that way (or, even better, be ripped out of the two as well).

If Buildah wants to support search behavior for the `FROM` value, it can do so; I can’t stop it. (And, in fact, AFAICS it does do that already for `Dockerfile` processing?! At least looking at `imagebuildah.Executor.Prepare`→`buildah.NewBuilder(…buildah.BuilderOptions.FromImage)`→`resolveImage`, which calls `util.ResolveName` and iterates over the input.  OTOH, you’re right that `buildah.Pull` only prepends the `docker://` prefix to the input, causing the `docker.io[/library]` normalization to be used.)

Anyway, the semantics of `docker://` is fixed to use the docker.io[/library] normalization, and if you want the search semantics to be used somewhere in buildah or its consumers, please seek in there.

**Comment by mtrmac** [comment]
Also, looking at https://github.com/openshift/builder/pull/40, note that `docker.AuthConfiguration` only contains an username+password, so it fundamentally can’t correctly support the search semantics, in which case multiple different authenticated registries may be present, and the code must not send credentials intended for one registry to other registries.

Just like the kubelet’s processing of image names when creating pods, this ultimately ends up with https://github.com/kubernetes/kubernetes/blob/a780dd78d30616c5bbf254244013d784a73c5d39/pkg/credentialprovider/keyring.go#L275-L280 , which hard-codes the `docker.io[/library]` normalization as well. In the Kubelet, the search mechanism was never usable, in general, for this reason — and for the same reason I can’t quite see how it was ever usable in the builder either (unless maybe the credentials were somehow shipped to the node in a node-global config file).
