### ISSUE TITLE
keyring ignores --authfile

### ISSUE THREAD

**Issue by vrothberg** [containers/image#662]
Libpod CI caught a regression from the recent keyring changes (see https://github.com/containers/libpod/pull/3598/checks?check_run_id=174300929). We shouldn't use the keyring when the user explicitly requests to use an auth file.

@QiWang19 PTAL

**Comment by QiWang19** [comment]
@vrothberg looking :eye: :eye:

**Comment by vrothberg** [comment]
For the record. It looks like the libpod CI was just flaky and is green now. Nonetheless, we should adhere to what the user has specified in the system context.

**Comment by mtrmac** [comment]
> We shouldn't use the keyring when the user explicitly requests to use an auth file.

… why? The --authfile option has historically been documented to configure the _path_ not to _turn on/off usage_.

(I’m not quite saying that using --authfile presence as an on/off switch is unreasonable, just that it is _not obvious_.)

**Comment by vrothberg** [comment]
If a user relies on the credentials being stored there (and maybe move the file around), it would now break.

However, you're right that it's not obvious and a quick man pages skim did not reveal a statement that the `--auth-file` will eventually be used or not.

**Comment by mtrmac** [comment]
Arguably the user could have relied on the credentials being stored in `~/.docker/config.json` just as well without explicitly specifying `--authfile`; we don’t know for sure.

OTOH forcing users to possibly specify two options on every command is also pretty unattractive… which is why I was arguing for an explicit `credHelper`/`credsStore` representation in the existing JSON. (I still need to catch up with all the conversation in #619 I’m afraid.)

**Comment by vrothberg** [comment]
Alright, just drop a note here.

@QiWang19, let's wait until we have a consensus how to proceed.

**Comment by mtrmac** [comment]
I feel reasonably confident that _if_ we want to allow users to explicitly choose to use a config file, we probably want to also allow them to explicitly choose to use the keyring.

OTOH how that option should be designed has another matter — should it just be a `credsStore` value (when neither “config file” nor ”keyring” are `credsStore` values at all). So that does not simplify things.

(See also how https://docs.docker.com/engine/reference/commandline/login/#credentials-store requires explicit opt-in into the macOS keychain.)

**Comment by rhatdan** [comment]
As a user, if I typed `--authfile $AUTHFILEPATH`  I would expect it to be honored, and we should document this behaviour.

**Comment by vrothberg** [comment]
> As a user, if I typed `--authfile $AUTHFILEPATH` I would expect it to be honored, and we should document this behaviour.

Do you mean we should document that it's not being honored and leave the new behaviour as is?

**Comment by rhatdan** [comment]
No I think we should honor it and document that it is honored.

**Comment by vrothberg** [comment]
> No I think we should honor it and document that it is honored.

:+1: will require updating the docs (and flag comments) in Skopeo, Buildah and Podman.

> I feel reasonably confident that if we want to allow users to explicitly choose to use a config file, we probably want to also allow them to explicitly choose to use the keyring.

I think we implicitly allowed this before already but we also have no idea if users are depending on it. Nonetheless, I agree that it sounds reasonable to let users chose which store they want to use.

**Comment by QiWang19** [comment]
I opened PR #668 and https://github.com/containers/libpod/pull/3674 to avoid keyring ignoring authfile
--authfile and REGISTRY_AUTH_DIR and be set to "nokeyring".  podman will return file path if "nokeyring" or filepath are set. 
In c/image credentials will be stored to kernel keyring if the AuthFilePath from libpod is empty.
