### ISSUE TITLE
We need a way to override the SigStoreStaging directory for rootless containers.

### ISSUE THREAD

**Issue by rhatdan** [containers/image#697]
Currently `podman image push --sign-by`
Does not work because it is attempting to write to /var/lib/atomic/sigstore by default.
There is no way for podman to override this while in rootless mode to something like
~/.local/share/containers/sigstore.

Should we make this part of the SystemContext?  And not hard code it in the config file, or at least allow it to be overridden by non root running applications.

**Comment by rhatdan** [comment]
@QiWang19 FYI.

**Comment by mtrmac** [comment]
There already is `SystemContext.RegistriesDirPath`; if the user really wants to use the sigstore mechanism with rootless, there should primarily be persistent config files, not per-command overrides. Adding individual overrides might make sense anyway, but it isn’t the first approach to explore.

(It might make some sense to use a per-user `registries.d` directory instead of the one in `/var` by default… OTOH the same files contain both the staging (write) and read paths, and if the environment is set up for signatures, reading should probably default to using the system-wide configuration.)

---

Really, the smoothest path to handle signatures is the X-R-S-S extension (and #385 ), not sigstore. If only it were widely available…

**Comment by rhatdan** [comment]
Well lets move forward on that. It has been sitting out there for nearly 2 years.  We need a solution for rootless. if this works I am all for it.

**Comment by rhatdan** [comment]
Yes that is fine, also.  We just need a different directory from root containers.

**Comment by mtrmac** [comment]
I think this was mostly fixed by #1035, which has a non-root default in `~/.local/share`.

@rhatdan Do we really need an option? Most applications should not override the defaults anyway.

**Comment by rhatdan** [comment]
I think we can go with the default sigstore for rootless, and close this issue.
