### ISSUE TITLE
Obsolete versions of docker libraries used

### ISSUE THREAD

**Issue by adambkaplan** [containers/image#772]
`containers/image` introduces a dependency on an outdated version of `docker/docker`. This has been moved to the Moby project, and many downstream projects replace `docker/docker` with `moby/moby` in their transitive dependencies.

If possible, `docker/docker` should be replaced with a recent version of `moby/moby`.

**Comment by mtrmac** [comment]
c/image uses very little from that repository, and is somewhat flexible to the version used. Historically, this IIRC was far more constrained by _users_ of c/image (like CRI-O or Podman, or some version of OpenShift) that use more of the subpackages, and have therefore more specific version requirements (including, from time to time, staying on earlier versions).

Go module dependencies are nowadays periodically updated; the `docker/docker` repo is not a module, so it would require manual review of the API impact, and coordination with consumers.

This is of course not a “no”, just a note that somewhat more work is involved than just updating c/image and making sure the tests continue to pass.

(Also, CRI-O and Podman continue to import `docker/docker`, so moving to the `moby/moby` name would increase binary sizes, not sure how much.)

**Comment by vrothberg** [comment]
I am not sure to fully understand the request.

Using `docker/docker` is effectively `moby/moby`. https://github.com/docker/docker is a redirect. All packages in `moby/moby` are referencing `docker/docker`, so changing any references would not have a functional impact. However, bumping the dependency to a newer commit would not hurt - although this has been quite hard in the past due to many consumers of c/image using outdated packages of docker where updates will break builds.

**Comment by mtrmac** [comment]
Looking at the immediately known consumers, c/image is quite behind:

Repo | Version
-----| -------
c/storage | v0.0.0-20171019062838-86f080cff091 // indirect
c/image | v0.0.0-20180522102801-da99009bbb11
c/libpod | v1.4.2-0.20191101170500-ac7306503d23
c/skopeo | v1.4.2-0.20191101170500-ac7306503d23
cri-o/cri-o | v1.4.2-0.20190927142053-ada3c14355ce

I guess that means updating to at least 201909… should be painless enough, `make test-skopeo` has been using the new version anyway.

(Skopeo uses a recent version because Dependabot does, ultimately, update the docker/docker repository if some other, Go module-packaged, dependency, requires a newer version. c/image does not have that dependency (`github.com/fsouza/go-dockerclient` in this case), so it is left behind.)

**Comment by mtrmac** [comment]
#874 has updated many dependencies, including docker/docker to 0.20191219165747-a9416c67da9f .
