### ISSUE TITLE
docker.io registry rewrites still apply the `library` suffix

### ISSUE THREAD

**Issue by saschagrunert** [containers/image#775]
Hey, I'm facing an issue where I'd like to discuss the solution approach before actually fixing the problem.

Let's assume that users push their docker.io mirrored images to `localhost:5000/docker.io` 

Then they rewrite a registry like this:
```toml
[[registry]]
prefix = "docker.io"
location = "localhost:5000/docker.io"
```

Now they expect that images pulled from `docker.io/image` get rewritten to `localhost:5000/docker.io/image`. Unfortunately, the internal docker ref normalization translates it to `localhost:5000/docker.io/library/image`.

What do we want to do? I see that we have this behavior everywhere when it comes to docker references so we might just document it appropriately. WDYT?

**Comment by mtrmac** [comment]
Yes, `prefix` (quite intentionally) does not do the `docker.io[/library]` normalization.
This should work, in general, if configured as
```
# For non-library namespaces
[[registry]]
prefix = "docker.io"
location = "localhost:5000/docker.io"

# The library namespace is more specific, so this stanza is preferred to the above
[[registry]]
prefix = "docker.io/library"
location = "localhost:5000/docker.io/library"
```
(and making appropriate modifications to the mirror’s configuration and mirroring scripts); does it?

---

Looking at the two-item example above, this also shows why we can’t drop `library` automatically: there isn’t a consistently correct way to mirror _both_ `docker.io/library/busybox` and `docker.io/busybox/foo`: if the mapping placed `docker.io/busybox/foo` to `localhost:5000/docker.io/busybox/foo`, but `docker.io/library/busybox` to `localhost:5000/docker.io/busybox`, the two hierarchies/administrative domains would be mixed.

(In practice, that is not _quite_ impossible right now because it isn’t possible to use a `docker://` reference to the `docker.io/[not library]/busybox` repository, so there isn’t currently an actual conflict in image _identities_, but it makes it impossible to e.g. treat the `library` set of images and a top-level `busybox` namespace on the mirror as separate, with e.g. separate admins / mirror scripts / permissions. And it could get worse in the future, AFAIK in principle nothing prevents `docker.io/library/busybox/foo` from existing, and at that point the conflict would be irreconcilable.)

---

I do agree this should be properly documented; it’s kind of implied reading between the lines if the reader knows about the `docker.io/library` mechanism at all, but many probably don’t.

**Comment by mtrmac** [comment]
> ```
> # For non-library namespaces
> [[registry]]
> prefix = "docker.io"
> location = "localhost:5000/docker.io"
> 
> # The library namespace is more specific, so this stanza is preferred to the above
> [[registry]]
> prefix = "docker.io/library"
> location = "localhost:5000/docker.io/library"
> ```
Oops, that’s nonsense and equivalent to the first entry only.

```
[[registry]
prefix = "docker.io/library"
location = "localhost:5000/docker.io"
```
is what I was thinking about, and it nicely illustrates the namespacing conflict.

**Comment by saschagrunert** [comment]
Thanks for the input @mtrmac, I appreciate it and will come up with a documentation "solution" (https://github.com/containers/image/pull/777).
