### ISSUE TITLE
Limit maximum concurrent layer pull

### ISSUE THREAD

**Issue by yangm97** [containers/image#776]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Although concurrent pulling usually speeds things up over broadband connections it will slow down or even fail a pull over a less than ideal connection.

The docker daemon has a `--max-concurrent-downloads` flag which allows the user to tune the image pull parallelism. Since we're daemonless that would need to be set on the config file or as a `pull/run/create` flag (or even both).

I looked into the code hoping to implement this myself and send a PR but I couldn't find where image pulling is done 😬.

**Comment by rhatdan** [comment]
I see this as an issue with CRI-O, perhaps but not sure this is something we should attempt to fix.  Preventing a user from running 100 podman commands at the same time?  Pulling images from a container registry?  Seems like a lot of complexity would need to be added to the code.  To me this is similar to someone firing off 100 curl/wget commands against a we server.  It is up to the web server/registry to protect itself.

**Comment by vrothberg** [comment]
I interpreted the request to limit the number of concurrent layer pulls in a single pull operation but not prevent other podmans or skopeos from pulling. At the moment, when an images has more than 1 layer we are pulling at most 6 layers in parallel. This can indeed cause problems in bad environments.

So it would not prevent other processes from pulling but just define how many go-routines can pull in parallel in one `c/image/copy` process.

**Comment by rhatdan** [comment]
Ok if it is per/process then I am fine with this.  I just wanted to avoid anything more complicated.
Not sure how the user/admin would specify this, but might be a good candidate for containers.conf.

**Comment by yangm97** [comment]
Yup, this issue is exactly as @vrothberg described it.

**Comment by mtrmac** [comment]
I don’t think `containers.conf` is quite the perfect place, because that would set a global limit regardless of context/operation: a local user running a single `podman pull`, and CRI-O starting hundreds of pods, would run on the same system but would have different latency vs. throughput vs. available bandwidth decisions.

It would make a bit more sense to me to expose this in `c/image/copy.Options`, and let individual callers (that need to care for some reason) provide options, whether on the CLI or in caller-specific configuration files. (OTOH, this does seem to be somewhat niche use case, and doing this in every single caller may not be worth the effort; not sure.)

**Comment by zgoda** [comment]
This is becoming painful now that I am mostly working from home and my connection is far from being stable. With 6 concurrent layer pulls it easily gets saturated resulting in pull failures.

**Comment by vrothberg** [comment]
Assigning to @rhatdan who wants to tackle it.

**Comment by mtrmac** [comment]
c/image now provides `copy.Options.MaxParallelDownloads` and `copy.Options.ConcurrentBlobCopiesSemaphore`.

https://github.com/containers/common/pull/415 then adds a config file option, presumably respected by Podman.

**Comment by vrothberg** [comment]
There's a knob in `man containers.conf` for that called "image_parallel_copied".

**Comment by deltawi** [comment]
Hey team any updates on this one ? I am facing the same issue with podman version 4.4.2. When on slow internet speed, it gives an error. This setting of concurrent parellel layer would reaally help.

**Comment by deltawi** [comment]
Thanks @mtrmac, not sure how to get to this file `containers.conf ` ? I am on Mac OS.

**Comment by pcgeek86** [comment]
This is still an issue in late 2025, almost 2026, for a slightly different reason than OP.

On a MacBook Pro M4 Max 64 GB, running MacOS Tahoe 26.2, I'm using the latest version of Docker Desktop 4.55 to pull a vLLM container image over a Starlink connection.

While the Docker Engine is pulling the container image, it drastically slows down other network traffic on my laptop, such as browsing GitHub, even to the point of timeout errors occurring.

It would be nice if there were an easy option of configuring the number of maximum, concurrent TCP connections used to download container image layers. Ideally it would be exposed as an option on the `docker pull` & `docker run` commands, so you can specify it during each operation, rather than specifying it globally for the Docker Desktop virtual machine.

**Comment by mtrmac** [comment]
Docker Desktop is not using this codebase at all.
