### ISSUE TITLE
Feature: glob / regex matcher for registry rewrites

### ISSUE THREAD

**Issue by saschagrunert** [containers/image#778]
Initiated by requests of users, it would be easier for them to specify less registry rewrites by the usage of glob or regex matching syntaxes. For example:

```toml
[[registry]]
prefix = " [^/]*$"
location = "my-local-registry.local/path"
```

I think it would be possible to implement in a clean way, but I have concerns regarding performance and the transparency of the actual rewrite. Especially regex is not really a standard and there might be misconfiguration because of the wrong regex _slang_.

What do you think? If we can agree that we want this feature I'd be happy to contribute it as well.

**Comment by Martin-Weiss** [comment]
Could we also add a wildcard to the "location target"?

Basically we have to replace this way, today:
```
[[registry]]
prefix = "registry.suse.com"
location = "myregistry01.domain.com:5000/kube-prod/registry.suse.com"
[[registry]]
prefix = "docker.io"
location = "myregistry01.domain.com:5000/kube-prod/docker.io"
[[registry]]
prefix = "docker.io/library"
location = "myregistry01.domain.com:5000/kube-prod/docker.io"
[[registry]]
prefix = "quay.io"
location = "myregistry01.domain.com:5000/kube-prod/quay.io"
[[registry]]
prefix = "k8s.gcr.io"
location = "myregistry01.domain.com:5000/kube-prod/k8s.gcr.io"
[[registry]]
prefix = "gcr.io"
location = "myregistry01.domain.com:5000/kube-prod/gcr.io"
```

So when defining the prefix / using the location it would be nice to have also "insert the prefix" in the target location:

i.e. something like this:

```
[[registry]]
prefix = " [^/]*$"
location = "myregistry01.domain.com:5000/kube-prod/%prefix%"
```

**Comment by saschagrunert** [comment]
We could achieve the wildcard by assigning the corresponding match groups of the regex, like:

```toml
[[registry]]
prefix = "my-registry.com/(.*)"
location = "myregistry01.domain.com:5000/kube-prod/\1"
```

Just depends on how much _magic_ should go in.

**Comment by vrothberg** [comment]
We had on-and-off discussions around that topic for a while. I need to lookup some of them to refresh my memory but I recall that there were some objections (need to look up) and some practical implications. For instance, how are wildcards treated in a "longest prefix wins" lookup?

> Just depends on how much magic should go in.

I prefer the less magic the better with no magic being the optimum. The quality and usability of something usually decreases with each `if ... then ... else` in its documentation.

```
[[registry]]
prefix = " [^/]*$"
location = "myregistry01.domain.com:5000/kube-prod/%prefix%"
```

One thing to consider is the maintenance cost of supporting that directly in c/image. It may be seen as an invite to add more and more things into `registries.conf` making it harder to maintain, more expensive, less approachable etc. Since `registries.conf` is TOML, it can easily be generated by another tool implementing a higher level syntax.

**Comment by Martin-Weiss** [comment]
Just as a side-note: the most important point is that when ever we have to change the registries.conf we have to restart crio which is a really costly action in a large environment.. due to that the wildcard feature and registry structure logic are important..

**Comment by saschagrunert** [comment]
> Just as a side-note: the most important point is that when ever we have to change the registries.conf we have to restart crio which is a really costly action in a large environment.. due to that the wildcard feature and registry structure logic are important..

Another side-note from my side: CRI-O v1.16.0 features a live configuration reload for registries, which can be done by sending SIGHUP to the `crio` daemon.

**Comment by Martin-Weiss** [comment]
> 
> 
> > Just as a side-note: the most important point is that when ever we have to change the registries.conf we have to restart crio which is a really costly action in a large environment.. due to that the wildcard feature and registry structure logic are important..
> 
> Another side-note from my side: CRI-O v1.16.0 features a live configuration reload for registries, which can be done by sending SIGHUP to the `crio` daemon.

Wow - cool - then we just might need the systemd timer that calls the SIGHUP on every change of the registries.conf (not sure if systemd reload crio would do the SIGHUP) and obviously a config management that allows re-distribution of registries.conf in an easy way when ever a new mapping is required ;-).

One other problem is that the ones managing the mappings (registries.conf) might be different persons than the ones deploying images/containers via i.e. helm charts.. so also here a wildcard would be useful..

**Comment by saschagrunert** [comment]
> > > Just as a side-note: the most important point is that when ever we have to change the registries.conf we have to restart crio which is a really costly action in a large environment.. due to that the wildcard feature and registry structure logic are important..
> > 
> > 
> > Another side-note from my side: CRI-O v1.16.0 features a live configuration reload for registries, which can be done by sending SIGHUP to the `crio` daemon.
> 
> Wow - cool - then we just might need the systemd timer that calls the SIGHUP on every change of the registries.conf (not sure if systemd reload crio would do the SIGHUP) and obviously a config management that allows re-distribution of registries.conf in an easy way when ever a new mapping is required ;-).

I think most distributions do something like this in the CRI-O systemd unit file which works:
```
ExecReload=/bin/kill -s HUP $MAINPID
```

**Comment by rhatdan** [comment]
Makes sense to me.

**Comment by mtrmac** [comment]
> For instance, how are wildcards treated in a "longest prefix wins" lookup?

Yes, this gets extremely messy. (It’s not unheard of, e.g. C++ method overloading finding a closest match, and I vaguely remember something defining preference for regex matches WRT specificity), but the design is never quite intuitive and the corner cases are a pain.

(In general, I am wary about mixing programming languages with options:
- “how dow you build a GUI for that”
- “how do you build an audit system that verifies $property”
- any such system is an API, making it impossible to change anything that would break such a programming language, i.e. impacting implementation decisions

Regexes are more on the language side than the option side. Of course, if it is worth writing software to generate settings in some situation, the software is likely going to exist at _some_ level. Of the three choices of 1) the thing being configured, 2) the configuration, and 3) the thing setting the configuration (if it is software), I tend to prefer 1 to 3 to 2.

But that’s a weak general preference with non-zero downsides, not a very strong argument to make one choice or the other in any specific case.)

---

> ```toml
> [[registry]]
> prefix = " [^/]*$"
> location = "my-local-registry.local/path"
> ```
What is this supposed to do? The matched prefixes don’t contain spaces.  Is it just an extra space, with the intent to try all references ever first by contacting that one local mirror?

---

Are there _actual_ needs for the full regex flexibility (character classes, ranges, alternatives, repetition)?

The “single local mirror” example given above is basically
```
[[registry]]
prefix = ""
location = "myregistry01.domain.com:5000/kube-prod"
```
and we wouldn’t need any regexes nor substitution. (Sure, that one does not currently work because empty `prefix` is a special case, there is one more/less `/` than necessary, and so on. But, conceptually, are you asking for this or actual regexes?)

Or maybe, alternatively, have a `prefixSet` + simple substitution? That might cover 80% of cases,  but it’s hard to cover all of them, and at that point just giving up and giving users the programming language might be simpler _for us_, at least, in that it reduces churn, at the cost of users dealing with the complexity every time.

**Comment by vrothberg** [comment]
We're currently going through open issues and PRs.  Given there's an alternative approach (i.e., by updating and reloading configs), I am going to close the issue.
