### ISSUE TITLE
docker-daemon: reference alpine has neither a tag nor a digest

### ISSUE THREAD

**Issue by knqyf263** [containers/image#792]
`skopeo inspect docker://alpine` succeeds, but `skopeo inspect docker-daemon:alpine` returns the following error.

```
FATA[0000] Error parsing image name "docker-daemon:alpine": docker-daemon: reference alpine has neither a tag nor a digest
```

An image with no `latest` tag causes this error. Is it intended? If no, can I insert `ref = reference.TagNameOnly(ref)` after the following line to add a `latest` tag?
https://github.com/containers/image/blob/7d9cde7252ecb039dae6082e885e4bd97bb75cae/docker/daemon/daemon_transport.go#L78

Actually, other transports use `TagNameOnly`.
https://github.com/containers/image/blob/de5ad242e515688f69225ca6d897cfb221e0f5c7/docker/archive/transport.go#L66
https://github.com/containers/image/blob/21244c96ad792ef415068dc1bc1ab82dffb68dc3/docker/docker_transport.go#L58

Let me know why only docker-daemon` doesn't use `TagNameOnly`, please.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @knqyf263! I think that should work but maybe I am missing something. At least, we state in the man pages that the docker-daemon supports docker:// references. Let's wait for @mtrmac's thoughts first.

**Comment by knqyf263** [comment]
@vrothberg Thank you for the quick response. I also think `docker-daemon:` should be the same as `docker://`, but this test expects a blank, so I'm wondering if this behavior is expected.
https://github.com/containers/image/blob/4d6079501ff668887e2b200d05a2c9ae79a8b156/docker/daemon/daemon_transport_test.go#L59

If @mtrmac says it is a bug, I will fix it. In that case, I'd ask how I should the above test because `reference.ParseAnyReference` doesn't add `latest` tag as well.
https://github.com/containers/image/blob/4d6079501ff668887e2b200d05a2c9ae79a8b156/docker/daemon/daemon_transport_test.go#L75

This means `daemonRef` returns `docker.io/library/busybox:latest`, while `dockerRef` returns `docker.io/library/busybox`.

Anyway, I'm waiting for his response. Thanks.

**Comment by mtrmac** [comment]
This is intentional, see https://github.com/containers/image/blob/110711adb69746436da9d31111db1359a2ac2539/docker/daemon/daemon_transport.go#L53 :

There isn’t really such a thing as “universal Docker reference” that applies to all the various transports and storage mechanisms with the same semantics.

`docker-daemon:` is conceptually an interface to the `docker save` / `docker load` facilities, and `docker save busybox` means “save _all_ images `busybox:$any-tag”`, so `docker-daemon:busybox` should in principle mean the same thing — which does not make sense as a reference to a single image.

(I can see the argument for defaulting to `:latest` here; I think being closer to the underlying semantics wins, but it’s not clearly the only possible design choice.)

The man page does implicitly suggest that untagged references are acceptable; that should be clarified if we stay with the current behavior.

**Comment by knqyf263** [comment]
Fair enough. But `docker inspect alpine` means `docker inspect alpine:latest`. IMHO, `skopeo inspect` should be the similar behavior. Besides, most users may not care about the underlying semantics (`docker save/load`) and be used to `docker run alpine` and `docker inspect alpine`.

On the other hand, I understand your thought. If you decide to keep the current behavior, I respect your idea and close this issue.

Thank you for this awesome library.

**Comment by mtrmac** [comment]
`skopeo` is not designed to be a drop-in replacement for `docker`, it already isn’t because it requires the `docker-daemon:` prefix anyway.

If you want a drop-in replacement that accepts the same syntax, use `podman`, which is actually designed to do that. E.g. `podman inspect` does default to `:latest` (note that it inspects the Podman’s container storage, which is separate from the Docker daemon storage, if you have both installed).

`skopeo inspect docker-daemon:alpine:latest` copies the _complete image_ (not just the inspect configuration, the full filesystem, which can be many gigabytes on large images) on disk _three times_ due to how it is implemented, so it really should not be used to interact with the Docker daemon storage if it is at all avoidable: any code doing that necessarily depends on the Docker code being present, so it can use `docker inspect` directly.

That’s not to say that we generally discourage interoperability or shared CLI patterns, but in _the particular case of `skopeo inspect docker-daemon:…`_, there are better options to steer the user to, so the motivation to make other compromises to make the CLI usage easier is particularly weak.

**Comment by knqyf263** [comment]
I got it. Thank you for your explanation!
