### ISSUE TITLE
Need a policy option for signatureIdentity match any.  

### ISSUE THREAD

**Issue by sjhx** [containers/image#807]
In the case where you only want to be assured that an image is signed by a trusted party, for example where a company is signing official images, the current policy schema does not allow you to write general policy rule to accept them.
It can be the case that an image is moved to a different repository (air-gap), its potentially one of the major benefits of simple signing that the signature remains valid when the image and signature is moved, or would be.
The "exactRepository" option is the nearest but requires that you have a rule for every source repository enumerated in advance, or maybe that the signer artificially sets the signedIdentity to a constant (bogus) repository.

Since we cannot use the absence of a signedIdentity element since the documentation defines the default enforcement, I suggest:
`"signedIdentity": { "type": "matchAny" }`

**Comment by mtrmac** [comment]
Thanks for your report.

So far, almost all of the people who say they want to only verify the public key also need to verify product versions (i.e. that they are installing the desired version instead of a five-year-old-one with many easily-exploitable vulnerabilities). All the threat models in which vendor-only signatures without product/version match enforcement are unusual and very restricted.

So, providing that option would make it too easy for such people to “get what they want” but not what they actually need, so I’m rather reluctant to make it available at all.

---

For air-gap scenarios, I would nowadays recommend:
- In all configuration (pod specifications, `Dockerfile`s), …, keep using the internet-wide image references (`registry.redhat.io/…`, `docker.io/…`), unmodified.
- Use the `registries.conf` mirror functionality ( https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md#remapping-and-mirroring-registries ) to redirect the internet-wide references to the local mirrors.

This makes the air gap an operations-only concern (configure the cluster nodes appropriately),  application developers don’t need to change their image references at all (i.e. the application and its setup is portable across clusters, whether disconnected or not), and it also automatically allows using the original image identities without any air-gap-specific configuration in `policy.json`.

The same approach to disconnected operation is used by the OpenShift disconnected operation support (ImageContentSourcePolicy).

(One notable downside to this design is that the `registries.conf` mirror functionality is invisible to the Kubelet, so pull secrets for the mirror, if any, can’t be pod-specific and have to be configured on the node.)

**Comment by sjhx** [comment]
Thanks @mtrmac, However I am clear that this is something we need to do, we are using the signature to indicate that a given image has passed a stage of approval at some point not what it is or whether it is the wanted version. For this another mechanism is appropriate. 

I think there is a danger that we will find another way to do as we want which will further fragment the options available. We want the rope in the full knowledge that we might hang ourselves. 

So far as your recommendation is concerned, we do not live in a world where all container image access is via the container/image library, a host based configuration is problematic in many ways e.g. multi-tenant, environments and in any case question the desirability of a solution which remaps the image reference “behind the scenes” leads to confusion.

**Comment by sjhx** [comment]
On the basis that we are discussing a more contolled/constrained options in https://github.com/containers/image/issues/884 which I agree are better I think we should close this one.
