### ISSUE TITLE
Wrong sigstore location on rootless podman push --sign-by

### ISSUE THREAD

**Issue by saschagrunert** [containers/image#835]
Reproducible with podman v1.8.0, If I want to use my local GPG keys to push signed images:

```bash
> podman pull docker.io/alpine
> podman tag docker.io/alpine quay.io/saschagrunert/alpine
> podman push --sign-by sgrunert@suse.com quay.io/saschagrunert/alpine
Error: Error copying image to the remote destination: Error writing signatures: mkdir /var/lib/containers/sigstore: permission denied
```

I think the issue is that `signatureTopLevel` returns the wrong path when running rootless:
https://github.com/containers/image/blob/143904cdaa199b9f3e0a19e1e2a965df10f1f0f9/docker/lookaside.go#L178-L190

If `write == true` then `ns.SigStoreStaging == "file:///var/lib/containers/sigstore"`

**Comment by mtrmac** [comment]
Thanks for your report.

What sigstore location were you expecting? This seems correct based on the default `/etc/containers/registries.d` path and the default contents https://github.com/containers/skopeo/blob/master/default.yaml , right now.

There is https://github.com/containers/image/issues/697 to have a per-user default for `registries.d`, and that could lead to per-user sigstore configuration / staging directories. But even that only suggests, but does not unavoidably imply, defaulting the staging location inside the home directory.

**Comment by saschagrunert** [comment]
When running rootless podman and doing `podman image sign …` then the sigstore is located somewhere in `.local/share/containers`. I think this is correct, so every user gets its own sigstore and can use its own gpg keys. So I expected to have the same sigstore when doing a `push`.

**Comment by mtrmac** [comment]
https://github.com/containers/libpod/blob/3bc5f431d4df9724501a42a68e333f7e98a0b0cf/cmd/podman/sign.go#L135

Ouch. That’s Podman, again, doing its own thing without considering any other c/image users at  all (not even its own `podman push`), and ignoring any actual administrator-created configuration.

I mean, that path is not an _unreasonable_ default but it is not _the_ default right now. We should consider changing this, OTOH just changing the default path could break some existing users that made `/var/lib/containers/sigstore` writable to a specific user, or, more likely, configured `/etc/containers/registries.d` with a non-default staging sigstore writable to a specific user.

**Comment by saschagrunert** [comment]
Alright I can spin-up a podman PR if nobody else is faster. I think it’s not that big deal to change the behavior in podman (last famous words), but I’m open to hear other opinions as well.

**Comment by mtrmac** [comment]
There isn’t a knob in c/image to override a sigstore for push/pull right now, only `RegistriesDirPath` . `podman image sign` can override the ultimate sigstore path only because it has copy&pasted the configuration lookup.

**Comment by saschagrunert** [comment]
> There isn’t a knob in c/image to override a sigstore for push/pull right now, only `RegistriesDirPath` . `podman image sign` can override the ultimate sigstore path only because it has copy&pasted the configuration lookup.

Ah so I guess it would be a proper way to add a way in overwriting it here, or maybe retrieving it from containers/storage :thinking:

**Comment by saschagrunert** [comment]
Btw, when running:
```
> sudo podman image sign ...
```
then the resulting sigstore is always `/var/lib/containers/sigstore`, independently what I've specified in `/etc/containers/registries.d/default.yaml`, like:

```yaml
default-docker:
  sigstore-staging: file:///var/lib/containers/another-sigstore
```

**Comment by mtrmac** [comment]
> > There isn’t a knob in c/image to override a sigstore for push/pull right now, only `RegistriesDirPath` . `podman image sign` can override the ultimate sigstore path only because it has copy&pasted the configuration lookup.
> 
> Ah so I guess it would be a proper way to add a way in overwriting it here via the (`copy.Options`), or maybe retrieving it from containers/storage 🤔

Ideally, this should not be something every single caller has to configure in `copy.Options` / `types.SystemContext` — and every single caller has to configure _the same way_.

But that seems hard: With the other config files which are now getting support for per-user locations, we use the per-user location if it exists, and fall back to the global config file. In this case, if there isn’t a per-user `registries.d` defaults file (or there isn’t a per-user `registries.d` directory, more likely), we would fall back to `/etc/containers/registries.d/default.yaml` and `/var/lib/…`

Even if we moved the `sigstore-staging: /var/lib/…` default from `default.yaml` into Go code, I can’t think of a _clear_ way to decide whether the default should be the system-wide one or a local one, other than based on EUID == 0 — but that’s fairly likely to break _some_ users.

Maybe we could add that EUID==0 logic as a built-in default, last in line after all config files, so that _existing_ systems use the `/etc/containers/registries.d/default.yaml` configuration unchanged, and _then_ drop that file or comment the contents out, so that _new_ systems decide based on EUID. Except that doesn’t work even with RPM-like upgrades, unmodified `default.yaml` would be replaced by a new version of the unmodified `default.yaml`; so that would have to be special-cased in every packaging (if it is even possible).

Even after solving the packaging issue, it would still be fragile: If the system administrator adds a `sigstore-staging` for root processes, non-root processes will start referring to it and failing, until the affected non-root users add their own per-user `registries.d` configuration (which we don’t currently even support).

---

(Another aspect to this is that with the sigstore-staging mechanism, `podman push --sign-by` or other ways to sign an image “silently does nothing without telling the user” — the signature is not consumable unless the user publishes it.

I think I have in the past argued that there should not a `default-docker:` `sigstore-staging:` value at all, and that we should fail signature writes unless the user makes an affirmative configuration (which implies the user is aware of the need to publish signatures separately; meanwhile registries with X-R-S-S could work by default without any extra configuration). 

OTOH assuming users that do know that the signatures need to be published, of course having a practical default path means one less step to deal with. Still, if we were looking for an excuse to punt on this, this one is still available.)
