### ISSUE TITLE
Move internal/pkg/platform package

### ISSUE THREAD

**Issue by crazy-max** [containers/image#868]
Hi @mtrmac,

I would like to use your [`platform.WantedPlatforms`](https://github.com/containers/image/tree/d85425defc5285493005e476e55a05c1acd69ed5/internal/pkg/platform) function but this is not possible to import internal packages of another package (https://golang.org/doc/go1.4#internalpackages). Would it be possible to outsource it? Something like `github.com/containers/image/pkg/platform` maybe?

Thanks!

**Comment by mtrmac** [comment]
In principle, sure, prepare a PR.

OTOH the package was originally internal because we didn’t want to block a necessary feature on designing a good long-term API, and without several relevant users it’s hard to guess how a good API should look like. (At the very least the `MatchesPlatform` name is unclear about direction.)

So, I was looking at https://github.com/crazy-max/diun/pull/56/files , and it’s unclear to me what the intent of the call is. The code _seems_ to be collecting properties of an image, but `WantedPlatforms` is not that — it’s either caller-provided data or properties of the runtime environment, so I don’t understand how it fits in here.

E.g. consider an ARM v5 image on in an ARM v7 environment (or with `types.SystemContext` specifying ARM v7): The _image_ is v5, and could have been chosen from a manifest list based on `WantedPlatforms`, but `WantedPlatforms`[0] is v7.

It seems to me that adding `Variant` to `InspectInfo` (as per https://github.com/containers/image/pull/865#issuecomment-604517552 ) would be a better fit — at least for Docker schema2 where the field is now defined, not OCI ( https://github.com/opencontainers/image-spec/pull/777 ). Does that make sense?

**Comment by crazy-max** [comment]
@mtrmac

> OTOH the package was originally internal because we didn’t want to block a necessary feature on designing a good long-term API, and without several relevant users it’s hard to guess how a good API should look like. (At the very least the MatchesPlatform name is unclear about direction.)

Okay thanks for the clarification

> So, I was looking at https://github.com/crazy-max/diun/pull/56/files , and it’s unclear to me what the intent of the call is. The code seems to be collecting properties of an image, but WantedPlatforms is not that — it’s either caller-provided data or properties of the runtime environment, so I don’t understand how it fits in here.

The information I want to collect in Diun concerns the target platform your package use when analyzing the image on a registry.  Is it possible to retrieve this property through `types.ImageCloser` obj?

> E.g. consider an ARM v5 image on in an ARM v7 environment (or with types.SystemContext specifying ARM v7): The image is v5, and could have been chosen from a manifest list based on WantedPlatforms, but WantedPlatforms[0] is v7.

I think that one concept escapes me in terms of interoperability of images. Does that mean that an ARM/v5 image is compatible on an ARM/v7 platform?

> It seems to me that adding Variant to InspectInfo (as per #865 (comment) ) would be a better fit — at least for Docker schema2 where the field is now defined, not OCI ( opencontainers/image-spec#777 ). Does that make sense?

Yes agree if you could that!

**Comment by mtrmac** [comment]
> The information I want to collect in Diun concerns the target platform your package use when analyzing the image on a registry.

For what purpose?

> Is it possible to retrieve this property through `types.ImageCloser` obj?

No. A `types.Image` is the result of the choice.

> > E.g. consider an ARM v5 image on in an ARM v7 environment (or with types.SystemContext specifying ARM v7): The image is v5, and could have been chosen from a manifest list based on WantedPlatforms, but WantedPlatforms[0] is v7.
> 
> I think that one concept escapes me in terms of interoperability of images. Does that mean that an ARM/v5 image is compatible on an ARM/v7 platform?

That’s the idea, and why `WantedPlatforms` returns an array. (Or isn’t that the case in the real world?)

There are two inputs:
- A manifest list of a multi-arch image, which points to the individual architecture/variant/OS-specific images. That’s a property _of the image_ (and can be inspected via a `c/image/manifest.List`, although that API may not currently give you everything you are looking for, I’m not sure what that is).
- The `WantedPlatform` result listing _all acceptable architecture/variant/OS combinations_. That’s a property _of the consumer_ (either the runtime environment, for running the image, or user’s choice for copying/inspecting/manipulating).

(e.g. for ARM, the manifest list could contain an ARM/v5 image (or _both_ and ARM/v5 image and an ARM/v7 image); and `WantedPlatforms` could contain (ARM/v7, ARM/v6, ARM/v6) in that order.)

The interaction of the image and the consumer’s request then determines which image in the manifest list is chosen.

**Comment by crazy-max** [comment]
> For what purpose?

This is purely informative, it allows the user to know to which platform the analysis of his image is associated. Do you want me to open a PR to add `Variant` to `InspectInfo` or is this being done on your end? 

> The interaction of the image and the consumer’s request then determines which image in the manifest list is chosen.

That makes sense, thanks!

**Comment by mtrmac** [comment]
A PR would be nice.

**Comment by crazy-max** [comment]
@mtrmac Ok done through #872
