### ISSUE TITLE
expose getCPUVariant/WantedPlatforms

### ISSUE THREAD

**Issue by grooverdan** [containers/image#876]
like #868 (which will probably help later - Thanks!),  I would like to see [getCPUVariant](https://github.com/containers/image/blob/master/internal/pkg/platform/platform_matcher.go#L108) exported to fill [this TODO in a PR for buildah](https://github.com/grooverdan/buildah/blob/args-target-platform/config.go#L98)

This code corresponds to the the `build --bud --platform Windows/arm64` to fill in the architecture variant correctly (after #875).

Alternately I could also take `WantedPlatforms`, with slightly more setup cost, (though passing `wantedOS` to `getCPUVariant(wantedOS, runtime.GOARCH)` seem more consistent).

I could be a bit muddled or trying to be to accepting of incomplete arguments than necessary so corrections/opinions gratefully accepted. As you've already decided to not get the Variant when provided an architecture what was the reasoning?

**Comment by mtrmac** [comment]
> I could be a bit muddled or trying to be to accepting of incomplete arguments than necessary so corrections/opinions gratefully accepted. As you've already decided to not get the Variant when provided an architecture what was the reasoning?

See https://github.com/containers/image/blob/06b89332d28f4b626c308df465512c827b15c8f4/internal/pkg/platform/platform_matcher.go#L132-L137 ; does that make sense?

(To an extent it’s an artifact of the API evolution, pre-existing callers that set `ArchitectureChoice` can’t opt out of variant autodetection which didn’t exist.)

---

>  I would like to see [getCPUVariant](https://github.com/containers/image/blob/master/internal/pkg/platform/platform_matcher.go#L108) exported to fill [this TODO in a PR for buildah](https://github.com/grooverdan/buildah/blob/args-target-platform/config.go#L98)
> 
> This code corresponds to the the `build --bud --platform Windows/arm64` to fill in the architecture variant correctly (after #875).

OK, that’s a clear enough use case.

I’m not quite sure whether to expose `getVariant` (as `GetRuntimeVariant`?), all of `WantedPlatforms` (maybe renamed?), or just the front half of `WantedPlatforms` that returns the current platform without computing the compatibility list.

Also, the public functions should probably have an error return value instead of silently returning `""` if `getCPUInfo` fails.

**Comment by grooverdan** [comment]
I think exposing `WantedPlatforms` probably renamed, though I'm struggling for a good one at the moment (`ResolvePlatform[s]`?). I'm happy to take the extra compatibility list (should it be used to generate multiple laters/tags? not sure), or ignore maybe if not needed. Given its a nice split in the middle its easy enough to add an abbreviated function later.

**Comment by mtrmac** [comment]
Looking at things like #904, we are really not sure what a stable API for WantedPlatforms should look like — that PR introduces new handling of `Variant: ""`, and we might add some kind of normalization to the output as well.

**Comment by mtrmac** [comment]
In the meantime, Buildah ended up using `c/common/libimage.NormalizePlatform`, built on top of `github.com/containerd/containerd/platforms`. That does more kinds of normalization that c/image, so c/image making this API public would not be sufficient.
